#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WebExtras.Core;
    using WebExtras.Mvc.Bootstrap;
    using WebExtras.Mvc.Bootstrap.v2;
    using WebExtras.Mvc.Core;
    using WebExtras.Mvc.Html;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Bootstrap/Views/Core/_AxisLabels.cshtml")]
    public partial class _Areas_Bootstrap_Views_Core__AxisLabels_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Bootstrap_Views_Core__AxisLabels_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<p>In order to draw axis labels you need <strong>jquery.flot.axislabels.js</stron" +
"g>.</p>\r\n\r\n<div class=\"well\">\r\n  <h4>Drawing axis labels</h4>\r\n  Axis labels can" +
" be drawn by setting the appropriate properties of the <strong>WebExtras.JQFlot." +
"SubOptions.AxisOptions</strong> class.\r\n  <pre><code>\r\n  AxisOptions axisOpt = n" +
"ew AxisOptions\r\n  {\r\n    axisLabel = \"my axis label\"\r\n  };\r\n  </code></pre>\r\n</d" +
"iv>\r\n\r\n<div class=\"well\">\r\n  <h4>Axis label options</h4>\r\n  <div class=\"content\"" +
">\r\n    <table class=\"table table-striped table-bordered\">\r\n      <tr>\r\n        <" +
"th>Option</th>\r\n        <th>Type</th>\r\n        <th>Default</th>\r\n        <th sty" +
"le=\"width: 45%\">Description</th>\r\n      </tr>\r\n      <tr>\r\n        <td>axisLabel" +
"</td>\r\n        <td>string</td>\r\n        <td><i>Empty string</i></td>\r\n        <t" +
"d>Axis label to be shown</td>\r\n      </tr>\r\n      <tr>\r\n        <td>axisLabelCol" +
"or</td>\r\n        <td>string</td>\r\n        <td><i>Color of grid</i></td>\r\n       " +
" <td>Axis label color to be used</td>\r\n      </tr>\r\n      <tr>\r\n        <td>axis" +
"LabelPadding</td>\r\n        <td>integer</td>\r\n        <td>2</td>\r\n        <td>Pad" +
"ding, in pixels, between the tick labels and the axis label</td>\r\n      </tr>\r\n " +
"     <tr>\r\n        <td>axisLabelUseCanvas</td>\r\n        <td>boolean</td>\r\n      " +
"  <td><i>None</i></td>\r\n        <td>Flag indicating whether to use the HTML5 Can" +
"vas element to render the axis labels</td>\r\n      </tr>\r\n      <tr>\r\n        <td" +
">axisLabelUseHtml</td>\r\n        <td>boolean</td>\r\n        <td>true</td>\r\n       " +
" <td>Flag indicating whether to use HTML and CSS transformations to render the a" +
"xis labels</td>\r\n      </tr>\r\n      <tr>\r\n        <td>axisLabelFontSizePixels</t" +
"d>\r\n        <td>int</td>\r\n        <td>14</td>\r\n        <td>Font size in pixels f" +
"or the axis label. This option is only available if \'axisLabelUseCanvas\' is set " +
"to true.</td>\r\n      </tr>\r\n      <tr>\r\n        <td>axisLabelFontFamily</td>\r\n  " +
"      <td>string</td>\r\n        <td>sans-serif</td>\r\n        <td>Font family for " +
"the axis label. This option is only available if \'axisLabelUseCanvas\' is set to " +
"true.</td>\r\n      </tr>\r\n    </table>\r\n    <div class=\"row-fluid\">\r\n      <div c" +
"lass=\"span12\">\r\n        <strong>Note:</strong> This plugin only works with Flot " +
"v0.7 and above since internally, it no longer takes into account the name of the" +
" axis \r\n        (i.e. yaxis, y2axis, etc.) but rather looks at the \'position\' va" +
"riable, which Flot automatically sets if it is not provided.\r\n      </div>\r\n    " +
"</div>\r\n  </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
