#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Bootstrap\Views\Core\Flot.cshtml"
    using SquishIt.Framework;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\Bootstrap\Views\Core\Flot.cshtml"
    using SquishIt.Mvc;
    
    #line default
    #line hidden
    using WebExtras.Core;
    
    #line 3 "..\..\Areas\Bootstrap\Views\Core\Flot.cshtml"
    using WebExtras.DemoApp.App_Start;
    
    #line default
    #line hidden
    using WebExtras.Mvc.Bootstrap;
    using WebExtras.Mvc.Bootstrap.v2;
    using WebExtras.Mvc.Core;
    using WebExtras.Mvc.Html;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Bootstrap/Views/Core/Flot.cshtml")]
    public partial class _Areas_Bootstrap_Views_Core_Flot_cshtml : System.Web.Mvc.WebViewPage<WebExtras.DemoApp.Models.Core.FlotViewModel>
    {
        public _Areas_Bootstrap_Views_Core_Flot_cshtml()
        {
        }
        public override void Execute()
        {



WriteLiteral("\r\n");


WriteLiteral("\r\n");


            
            #line 7 "..\..\Areas\Bootstrap\Views\Core\Flot.cshtml"
  
  ViewBag.Title = "jQuery Flot";


            
            #line default
            #line hidden
WriteLiteral("\r\n");


DefineSection("scripts", () => {

WriteLiteral("\r\n  ");


            
            #line 13 "..\..\Areas\Bootstrap\Views\Core\Flot.cshtml"
Write(Bundle.JavaScript().MvcRenderCachedAssetTag(ContentBundle.JSFlot.GetStringValue()));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


});

WriteLiteral(@"

<h3 class=""keep-center"">jQuery Flot Bindings</h3>

<div class=""row-fluid"">
  <div class=""span6"">
    <div class=""row-fluid"">
      <div class=""span3"">
        <strong>Assembly</strong>
      </div>
      <div class=""span4"">
        WebExtras.dll
      </div>
    </div>
    <div class=""row-fluid"">
      <div class=""span3"">
        <strong>Namespace</strong>
      </div>
      <div class=""span4"">
        WebExtras.JQFlot
      </div>
    </div>
  </div>
  <div class=""span6"">
    <div class=""span3"">
      <strong>Dependancies</strong>
    </div>
    <div class=""span6"">
      <ul class=""dependancies"">
        <li>Appropriate third party libraries</li>
        <li>webextras.bootstrap.css</li>
      </ul>
    </div>
  </div>
</div>
<div class=""row-fluid"">
  <div class=""span9"">
    Steps involved in creating a Flot graph
    <ul>
      <li>Creating graph options</li>
      <li>Creating graph data</li>
      <li>Creating the graph series</li>
      <li>Rendering the graph</li>
    </ul>
  </div>
</div>
<ul id=""flot-nav"" class=""nav nav-pills"">
  <li>");


            
            #line 61 "..\..\Areas\Bootstrap\Views\Core\Flot.cshtml"
 Write(Html.ActionLink("Line Graph", MVC.Bootstrap.Core.Flot(0)));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n  <li>");


            
            #line 62 "..\..\Areas\Bootstrap\Views\Core\Flot.cshtml"
 Write(Html.ActionLink("Dashed Line Graph", MVC.Bootstrap.Core.Flot(1)));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n  <li>");


            
            #line 63 "..\..\Areas\Bootstrap\Views\Core\Flot.cshtml"
 Write(Html.ActionLink("Curved Line Graph", MVC.Bootstrap.Core.Flot(2)));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n  <li>");


            
            #line 64 "..\..\Areas\Bootstrap\Views\Core\Flot.cshtml"
 Write(Html.ActionLink("Bar Graph", MVC.Bootstrap.Core.Flot(3)));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n  <li>");


            
            #line 65 "..\..\Areas\Bootstrap\Views\Core\Flot.cshtml"
 Write(Html.ActionLink("Pie Graph", MVC.Bootstrap.Core.Flot(4)));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n  <li>");


            
            #line 66 "..\..\Areas\Bootstrap\Views\Core\Flot.cshtml"
 Write(Html.ActionLink("Axis Labels", MVC.Bootstrap.Core.Flot(5)));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n  <li>");


            
            #line 67 "..\..\Areas\Bootstrap\Views\Core\Flot.cshtml"
 Write(Html.ActionLink("Custom Formatters", MVC.Bootstrap.Core.Flot(6)));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n</ul>\r\n\r\n<script type=\"text/javascript\">\r\n  $(document).ready(function () " +
"{\r\n    $(\'#flot-nav li:eq(\' + ");


            
            #line 72 "..\..\Areas\Bootstrap\Views\Core\Flot.cshtml"
                      Write(Model.DisplayMode);

            
            #line default
            #line hidden
WriteLiteral(" + \')\').addClass(\'active\');\r\n  });\r\n</script>\r\n\r\n");


            
            #line 76 "..\..\Areas\Bootstrap\Views\Core\Flot.cshtml"
 switch (Model.DisplayMode)
{
  case 6:
  
            
            #line default
            #line hidden
            
            #line 79 "..\..\Areas\Bootstrap\Views\Core\Flot.cshtml"
Write(Html.Partial(MVC.Core.Views._CustomFlotFormatters, Model.Chart));

            
            #line default
            #line hidden
            
            #line 79 "..\..\Areas\Bootstrap\Views\Core\Flot.cshtml"
                                                                  
    break;

  case 5:
  
            
            #line default
            #line hidden
            
            #line 83 "..\..\Areas\Bootstrap\Views\Core\Flot.cshtml"
Write(Html.Partial(MVC.Bootstrap.Core.Views._AxisLabels));

            
            #line default
            #line hidden
            
            #line 83 "..\..\Areas\Bootstrap\Views\Core\Flot.cshtml"
                                                     
    break;

  case 4:
  
            
            #line default
            #line hidden
            
            #line 87 "..\..\Areas\Bootstrap\Views\Core\Flot.cshtml"
Write(Html.Partial(MVC.Core.Views._PieGraph, Model.Chart));

            
            #line default
            #line hidden
            
            #line 87 "..\..\Areas\Bootstrap\Views\Core\Flot.cshtml"
                                                      
    break;

  case 3:
  
            
            #line default
            #line hidden
            
            #line 91 "..\..\Areas\Bootstrap\Views\Core\Flot.cshtml"
Write(Html.Partial(MVC.Core.Views._BarGraph, Model.Chart));

            
            #line default
            #line hidden
            
            #line 91 "..\..\Areas\Bootstrap\Views\Core\Flot.cshtml"
                                                      
    break;

  case 2:
  
            
            #line default
            #line hidden
            
            #line 95 "..\..\Areas\Bootstrap\Views\Core\Flot.cshtml"
Write(Html.Partial(MVC.Core.Views._CurvedLineGraph, Model.Chart));

            
            #line default
            #line hidden
            
            #line 95 "..\..\Areas\Bootstrap\Views\Core\Flot.cshtml"
                                                             
    break;

  case 1:
  
            
            #line default
            #line hidden
            
            #line 99 "..\..\Areas\Bootstrap\Views\Core\Flot.cshtml"
Write(Html.Partial(MVC.Core.Views._DashedGraph, Model.Chart));

            
            #line default
            #line hidden
            
            #line 99 "..\..\Areas\Bootstrap\Views\Core\Flot.cshtml"
                                                         
    break;

  default:
  
            
            #line default
            #line hidden
            
            #line 103 "..\..\Areas\Bootstrap\Views\Core\Flot.cshtml"
Write(Html.Partial(MVC.Core.Views._LineGraph, Model.Chart));

            
            #line default
            #line hidden
            
            #line 103 "..\..\Areas\Bootstrap\Views\Core\Flot.cshtml"
                                                       
    break;
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
