#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Core/_AjaxSetup.cshtml")]
    public partial class _Views_Core__AjaxSetup_cshtml : System.Web.Mvc.WebViewPage<WebExtras.JQDataTables.Datatable>
    {
        public _Views_Core__AjaxSetup_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n<p>\r\n  When populating via AJAX source, all you need to do is set the AJAX sour" +
"ce parameter on the Datatable settings\r\n      contructor\r\n</p>\r\n<div class=\"well" +
" ui-well\">\r\n  <h4>Creating table settings</h4>\r\n  Table settings are created by " +
"instantiating the <i>WebExtras.JQDataTables.DatatableSettings</i> class \r\n  <pre" +
"><code>  \r\n  DatatableSettings dtSettings = new DatatableSettings \r\n  (\r\n    5, " +
"                                     <span class=\"comment\">// specify the number" +
" of records per page</span>\r\n    dtColumns,\r\n    new AASort(0, ESort.Ascending)," +
"         <span class=\"comment\">// specify one initial sort, multiple initial sor" +
"ts, or leave null for no sort</span>\r\n    <span class=\"highlight\">\"~/getajaxdata" +
"\"</span>,                       <span class=\"comment\">// specify an AJAX source " +
"to retrieve data from</span>\r\n    \"ajax records\",                         <span " +
"class=\"comment\">// specify a table footer suffix</span>\r\n    \"150px\"            " +
"                     <span class=\"comment\">// specify a maximum table height, on" +
"ce reached you will get scroll bars</span>\r\n  );\r\n  </code></pre>\r\n</div>\r\n\r\n<di" +
"v class=\"well ui-well\">\r\n  <h4>Creating the AJAX callback handler action</h4>\r\n " +
" In order to populate data with an AJAX callback, you will obviously need a call" +
" back action/page/request handler which returns JSON formatted data.\r\n  This exa" +
"mple uses a .NET MVC controller action, however you are not limited to that. All" +
" you need is for the server to accept some parameters\r\n  from a client HTTP GET " +
"request, process the data accordingly and return the JSON formatted table data.\r" +
"\n  <pre><code>\r\n  public JsonResult GetAjaxData(DatatableFilters filters)\r\n  {\r\n" +
"    <span class=\"comment\">// Let\'s create the actual data to go into the table</" +
"span>\r\n    <span class=\"comment\">// You can retrieve data from your repository h" +
"ere</span>\r\n    string[][] dtData = new string[][]\r\n    {\r\n      new string[] { " +
"\"first column ajax row 1\", \"second column ajax row 1\" },    \r\n      new string[]" +
" { \"first column ajax row 2\", \"second column ajax row 2\" }\r\n    };\r\n\r\n    Datata" +
"bleRecords dtRecords = new DatatableRecords\r\n    {\r\n      sEcho = filters.sEcho," +
"\r\n      iTotalRecords = dtData.Length,                      <span class=\"comment" +
"\">// Total records in table</span>\r\n      iTotalDisplayRecords = dtData.Length, " +
"              <span class=\"comment\">// Total records to be displayed in the tabl" +
"e</span>\r\n      aaData = dtData                                     <span class=" +
"\"comment\">// The data to be displayed</span>\r\n    };\r\n\r\n    return Json(dtRecord" +
"s, JsonRequestBehavior.AllowGet);\r\n  }\r\n  </code></pre>\r\n  DatatableFilters clas" +
"s is just an entity class which makes use of the .NET MVC auto binding feature t" +
"o look at the request parameters\r\n  and try to populate the appropriate attribut" +
"es of the class. If you are not using .NET MVC, your request handler definition " +
"would look\r\n  something like this:\r\n  <pre><code>\r\n  public string GetAjaxData(s" +
"tring sEcho, \r\n    string sSearch, \r\n    int iDisplayLength, \r\n    int iDisplayS" +
"tart, \r\n    int iColumns, \r\n    int iSortingCols, \r\n    int iSortCol_0, \r\n    st" +
"ring sSortDir_0, \r\n    string sColumns)\r\n  </code></pre>\r\n</div>\r\n\r\n<div class=\"" +
"well ui-well\">\r\n  <h4>And the output is</h4>\r\n  <div class=\"output\">\r\n    ");


            
            #line 69 "..\..\Views\Core\_AjaxSetup.cshtml"
Write(Html.Partial(MVC.Shared.Views.DatatablePartial, Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n  </div>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
