#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Core/_BarGraph.cshtml")]
    public partial class _Views_Core__BarGraph_cshtml : System.Web.Mvc.WebViewPage<WebExtras.JQFlot.FlotChart>
    {
        public _Views_Core__BarGraph_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral(@"
<div class=""well ui-well"">
  <h4>Slightly modifying our series we get...</h4>
  <pre><code>
  FlotSeries serie = new FlotSeries
  {
    label = ""Sample Bar Graph"",
    data = graphData,
    dashes = new BarGraph { show = true }                 <span class=""comment"">// This will denote that you want a Bar graph</span>
  };
  </code></pre>
</div>

<div class=""well ui-well"">
  <h4>And we have a bar graph...</h4>
  <div class=""content"">    
    <div id=""bar-graph"" class=""graph"">
    </div>
  </div>
  <script type=""text/javascript"">
    $(document).ready(function () {
      $.plot($('#bar-graph'), [");


            
            #line 23 "..\..\Views\Core\_BarGraph.cshtml"
                          Write(Html.Raw(Model.chartSeries[0].ToString()));

            
            #line default
            #line hidden
WriteLiteral("], ");


            
            #line 23 "..\..\Views\Core\_BarGraph.cshtml"
                                                                       Write(Html.Raw(Model.chartOptions.ToString()));

            
            #line default
            #line hidden
WriteLiteral(");    \r\n    });\r\n  </script>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
