#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WebExtras.Core;
    using WebExtras.Mvc.Core;
    using WebExtras.Mvc.Html;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Core/_BasicSetup.cshtml")]
    public partial class _Views_Core__BasicSetup_cshtml : System.Web.Mvc.WebViewPage<WebExtras.JQDataTables.Datatable>
    {
        public _Views_Core__BasicSetup_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n<div class=\"well ui-well\">\r\n  <h4>Creating column definitions</h4>\r\n  Column de" +
"finitions are created by instantiating the <i>WebExtras.JQDataTables.AOColumn</i" +
"> class\r\n  <pre><code>\r\n  AOColumn dtColumn = new AOColumn\r\n  {\r\n      sTitle = " +
"\"First Column\",    <span class=\"comment\">// Only the sTitle property is compulso" +
"ry. All other properties are optional</span>\r\n      bSortable = true,\r\n      sCl" +
"ass = \"\",                <span class=\"comment\">// any extra CSS class you would " +
"like to apply to this column</span>\r\n      sWidth = \"10%\",             <span cla" +
"ss=\"comment\">// specified as a CSS width</span>\r\n      bVisible = true\r\n  };  \r\n" +
"  </code></pre>\r\n</div>\r\n\r\n<div class=\"well ui-well\">\r\n  <h4>Creating table sett" +
"ings</h4>\r\n  Table settings are created by instantiating the <i>WebExtras.JQData" +
"Tables.DatatableSettings</i> class \r\n  <pre><code>  \r\n  <span class=\"comment\">//" +
" We need a collection of columns to be specified in the settings, so create an a" +
"rray from our column</span>\r\n  AOColumn[] dtColumns = new AOColumn[] { dtColumn " +
"};\r\n\r\n  DatatableSettings dtSettings = new DatatableSettings \r\n  (\r\n    5,      " +
"                                <span class=\"comment\">// specify the number of r" +
"ecords per page</span>\r\n    dtColumns,                              <span class=" +
"\"comment\">// Column definitions</span>\r\n    new AASort(0, ESort.Ascending),     " +
"    <span class=\"comment\">// specify one initial sort, multiple initial sorts, o" +
"r leave null for no sort</span>\r\n    null,                                   <sp" +
"an class=\"comment\">// specify an AJAX source to retrieve data from</span>\r\n    \"" +
"basic records\",                        <span class=\"comment\">// specify a table " +
"footer suffix</span>\r\n    \"150px\"                                 <span class=\"c" +
"omment\">// specify a maximum table height, once reached you will get scroll bars" +
"</span>\r\n  );\r\n  </code></pre>\r\n</div>\r\n\r\n<div class=\"well ui-well\">\r\n  <h4>Crea" +
"ting table records</h4>\r\n  Table records are created by instantiating the <i>Web" +
"Extras.JQDataTables.DatatableRecords</i> class\r\n  <pre><code>\r\n  <span class=\"co" +
"mment\">// Let\'s create the actual data to go into the table</span>\r\n  string[][]" +
" dtData = new string[][]\r\n  {\r\n    new string[] { \"first column row 1\" },\r\n    n" +
"ew string[] { \"first column row 2\" }\r\n  };\r\n\r\n  DatatableRecords dtRecords = new" +
" DatatableRecords\r\n  {\r\n    iTotalRecords = dtData.Length,            <span clas" +
"s=\"comment\">// Total records in table</span>\r\n    iTotalDisplayRecords = dtData." +
"Length,     <span class=\"comment\">// Total records to be displayed in the table<" +
"/span>\r\n    aaData = dtData                           <span class=\"comment\">// T" +
"he data to be displayed</span>\r\n  };\r\n  </code></pre>\r\n</div>\r\n\r\n<div class=\"wel" +
"l ui-well\">\r\n  <h4>Creating the table object</h4>\r\n  Let us now bring all the di" +
"fferent components together\r\n  <pre><code>\r\n  <span class=\"comment\">// Let\'s cre" +
"ate the datatable object with an HTML ID, our settings and records</span>\r\n  Dat" +
"atable dtable = new Datatable(\"demo-table\", dtSettings, dtRecords);\r\n  </code></" +
"pre>\r\n</div>\r\n\r\n<div class=\"well ui-well\">\r\n  <h4>Now let\'s see the output</h4>\r" +
"\n  <div class=\"output\">\r\n    ");


            
            #line 69 "..\..\Views\Core\_BasicSetup.cshtml"
Write(Html.Partial(MVC.Shared.Views._Datatable, Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n  </div>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
