#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Core/_DashedGraph.cshtml")]
    public partial class _Views_Core__DashedGraph_cshtml : System.Web.Mvc.WebViewPage<WebExtras.JQFlot.FlotChart>
    {
        public _Views_Core__DashedGraph_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral(@"
<p>
  In order to draw <strong>dashed line graphs</strong> you need <strong>jquery.flot.dashed.js</strong> i.e the
  dashed graph plugin.
</p>

<div class=""well ui-well"">
  <h4>Slightly modifying our series we get...</h4>
  <pre><code>
  FlotSeries serie = new FlotSeries
  {
    label = ""Sample Dashed Line Graph"",
    data = graphData,
    dashes = new DashedLineGraph { show = true }                 <span class=""comment"">// This will denote that you want a Dashed Line graph</span>
  };
  </code></pre>
</div>

<div class=""well ui-well"">
  <h4>And we have a dashed graph...</h4>
  <div class=""content"">    
    <div id=""dashed-graph"" class=""graph"">
    </div>
  </div>
  <script type=""text/javascript"">
    $(document).ready(function () {
      $.plot($('#dashed-graph'), [");


            
            #line 28 "..\..\Views\Core\_DashedGraph.cshtml"
                             Write(Html.Raw(Model.chartSeries[0].ToString()));

            
            #line default
            #line hidden
WriteLiteral("], ");


            
            #line 28 "..\..\Views\Core\_DashedGraph.cshtml"
                                                                          Write(Html.Raw(Model.chartOptions.ToString()));

            
            #line default
            #line hidden
WriteLiteral(");    \r\n    });\r\n  </script>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
