#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WebExtras.Core;
    using WebExtras.Mvc.Core;
    using WebExtras.Mvc.Html;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Core/_JQPlotOHLCGraph.cshtml")]
    public partial class _Views_Core__JQPlotOHLCGraph_cshtml : System.Web.Mvc.WebViewPage<WebExtras.JQPlot.JQPlotChartBase>
    {
        public _Views_Core__JQPlotOHLCGraph_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n<p>\r\n  OHLC, HLC and Candlestick charts are all created using jqPlot\'s OHLC ren" +
"derer plugin. \r\n  The plots on this page make use of the highlighter plugin whic" +
"h shows a customized tooltip \r\n  as the mouse moves over a data point.\r\n</p>\r\n\r\n" +
"<div class=\"well ui-well\">\r\n  <h4>How your data will look</h4>\r\n  <pre><code>\r\n " +
" <span class=\"comment\">// Your data will look something like this</span>\r\n  obje" +
"ct[][] data = new object[][] {\r\n    new object[] { \"01-Jan-2014 13:23:11\", 100.7" +
", 123.4, 134.1, 123.4  }\r\n    ...\r\n    ...\r\n    ...\r\n  }\r\n  </code></pre>\r\n</div" +
">\r\n\r\n<div class=\"well ui-well\">\r\n  <h4>Your plot options</h4>\r\n  <pre><code>\r\n  " +
"<span class=\"comment\">// This is just for ease of specifying the format string</" +
"span>\r\n  StringBuilder formatStringBuilder = new StringBuilder();\r\n  formatStrin" +
"gBuilder.Append(\"&lt;table class=\'jqplot-highlighter\'&gt;\");\r\n  formatStringBuil" +
"der.Append(\"&lt;tr&gt;&lt;td&gt;date:&lt;/td&gt;&lt;td&gt;%s&lt;/td&gt;&lt;/tr&g" +
"t;\");\r\n  formatStringBuilder.Append(\"&lt;tr&gt;&lt;td&gt;open:&lt;/td&gt;&lt;td&" +
"gt;%s&lt;/td&gt;&lt;/tr&gt;\");\r\n  formatStringBuilder.Append(\"&lt;tr&gt;&lt;td&g" +
"t;hi:&lt;/td&gt;&lt;td&gt;%s&lt;/td&gt;&lt;/tr&gt;\");\r\n  formatStringBuilder.App" +
"end(\"&lt;tr&gt;&lt;td&gt;low:&lt;/td&gt;&lt;td&gt;%s&lt;/td&gt;&lt;/tr&gt;\");\r\n " +
" formatStringBuilder.Append(\"&lt;tr&gt;&lt;td&gt;close:&lt;/td&gt;&lt;td&gt;%s&l" +
"t;/td&gt;&lt;/tr&gt;\");\r\n  formatStringBuilder.Append(\"&lt;/table&gt;\");\r\n\r\n  op" +
"tions = new JQPlotOptions\r\n  {\r\n    seriesDefaults = new JQPlot.SubOptions.Serie" +
"sOptions\r\n    {\r\n      yaxis = \"y2axis\"\r\n    },\r\n    axes = new JQPlotAxes\r\n    " +
"{\r\n      xaxis = new JQPlot.SubOptions.AxisOptions\r\n      {\r\n        renderer = " +
"EJQPlotRenderer.DateAxisRenderer,\r\n        tickOptions = new AxisTickRendererOpt" +
"ions\r\n        {\r\n          formatString = \"%b %e\"\r\n        },\r\n        tickInter" +
"val = \"6 weeks\"\r\n      },\r\n      y2axis = new JQPlot.SubOptions.AxisOptions\r\n   " +
"   {\r\n        tickOptions = new AxisTickRendererOptions\r\n        {\r\n          fo" +
"rmatString = \"$%d\"\r\n        }\r\n      }\r\n    },\r\n    series = new JQPlot.SubOptio" +
"ns.SeriesOptions[] {\r\n      new JQPlot.SubOptions.SeriesOptions {\r\n        rende" +
"rer = <span class=\"highlight\">EJQPlotChartRenderer.OHLCRenderer</span>,  <span c" +
"lass=\"comment\">// Notice that we are specifying we want OHLC renderer</span>\r\n  " +
"      rendererOptions = new OHLCRendererOptions {\r\n          candleStick = true\r" +
"\n        }\r\n      }\r\n    },\r\n    highlighter = new HighlighterOptions\r\n    {\r\n  " +
"    show = true,\r\n      showMarker = false,\r\n      tooltipAxes = \"xy\",\r\n      yv" +
"alues = 4,\r\n      formatString = formatStringBuilder.ToString()       <span clas" +
"s=\"comment\">// We are using the format string we created above</span>\r\n    }\r\n  " +
"};\r\n</code></pre>\r\n</div>\r\n\r\n<div class=\"well ui-well\">\r\n  <h4>And finally your " +
"OHLC chart</h4>\r\n  <div class=\"content\">\r\n    <div id=\"ohlc-graph\" class=\"graph " +
"graph-large\">\r\n    </div>\r\n    <br />\r\n    Required Plugins:<br />\r\n    <ul>\r\n  " +
"    <li>jqplot.dateAxisRenderer.min.js</li>\r\n      <li>jqplot.ohlcRenderer.min.j" +
"s</li>\r\n      <li>jqplot.highlighter.min.js</li>\r\n    </ul>\r\n  </div>\r\n  <script" +
" type=\"text/javascript\">\r\n    $(document).ready(function () {\r\n\r\n      $.jqplot(" +
"\'ohlc-graph\', ");


            
            #line 96 "..\..\Views\Core\_JQPlotOHLCGraph.cshtml"
                        Write(Html.Raw(Model.chartData.ToJson()));

            
            #line default
            #line hidden
WriteLiteral(", ");


            
            #line 96 "..\..\Views\Core\_JQPlotOHLCGraph.cshtml"
                                                             Write(Html.Raw(Model.chartOptions.ToString()));

            
            #line default
            #line hidden
WriteLiteral(");\r\n    });\r\n  </script>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
