#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WebExtras.Core;
    using WebExtras.Mvc.Core;
    using WebExtras.Mvc.Html;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Core/_JQPlotNonNumericAxisValues.cshtml")]
    public partial class _Views_Core__JQPlotNonNumericAxisValues_cshtml : System.Web.Mvc.WebViewPage<WebExtras.JQPlot.JQPlotChartBase[]>
    {
        public _Views_Core__JQPlotNonNumericAxisValues_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n<div class=\"well ui-well\">\r\n  <h4>X axis values as text</h4>\r\n  <pre><code>\r\n  " +
"  object[][] data = new object[][] { \r\n      new object[] { \"Cup Holder Pinion B" +
"ob\", 7 },\r\n      new object[] { \"Generic Fog Lamp\", 9 },\r\n      new object[] { \"" +
"HDTV Receiver\", 15 },\r\n      new object[] { \"8 Track Control Module\", 12 },\r\n   " +
"   new object[] { \"Sludge Pump Fourier Modulator\", 3 },\r\n      new object[] { \"T" +
"ranscender/Spice Rack\", 6 },\r\n      new object[] { \"Hair Spray Danger Indicator\"" +
", 18 }\r\n    };\r\n  </code></pre>\r\n</div>\r\n\r\n\r\n<div class=\"well ui-well\">\r\n  <h4>M" +
"odified plot options</h4>\r\n  <pre><code>\r\n  JQPlotOptions options = new JQPlotOp" +
"tions\r\n  {\r\n    title = new TitleOptions(\"Concern vs Occurance\"),\r\n    axesDefau" +
"lts = new JQPlot.SubOptions.AxisOptions\r\n    {\r\n      tickRenderer = EJQPlotRend" +
"erer.CanvasAxisTickRenderer,\r\n      tickOptions = new Dictionary&lt;string, obje" +
"ct&gt; {\r\n        <span class=\"comment\">// Specifies the tilt angle for axis tic" +
"ks at -30&deg;</span> \r\n        { \"angle\", -30 }                                " +
"  \r\n      }\r\n    },\r\n    axes = new JQPlotAxes\r\n    {\r\n      xaxis = new JQPlot." +
"SubOptions.AxisOptions { renderer = EJQPlotRenderer.CategoryAxisRenderer },\r\n   " +
"   yaxis = new JQPlot.SubOptions.AxisOptions\r\n      {\r\n        tickOptions = new" +
" Dictionary&lt;string, object&gt; { \r\n          <span class=\"comment\">// Explici" +
"tly overrides and resets the tilt angle for Y axis ticks to 0&deg;</span>\r\n     " +
"     { \"angle\", 0 }                                  \r\n        }\r\n      }\r\n    }" +
"\r\n  };\r\n  </code></pre>\r\n</div>\r\n\r\n<div class=\"well ui-well\">\r\n  <h4>Setting up " +
"the plot object</h4>\r\n  <pre><code>\r\n  <span class=\"comment\">// Note that we are" +
" instantiating a <span class=\"highlight\">JQPlotChartBase</span> object and NOT a" +
" <span class=\"highlight\">JQPlotChart</span> object</span>\r\n  <span class=\"commen" +
"t\">// This allows us to create a multi datatype data array</span>\r\n  JQPlotChart" +
"Base chart = new JQPlotChartBase\r\n  {\r\n    chartData = new List&lt;object[][]&gt" +
"; { data },\r\n    chartOptions = options\r\n  };\r\n  </code></pre>\r\n</div>\r\n\r\n<div c" +
"lass=\"well ui-well\">\r\n  <h4>And the output is...</h4>\r\n  <div class=\"content\">\r\n" +
"    <div id=\"non-numeric-axis-values-graph\" class=\"graph graph-large\">\r\n    </di" +
"v>\r\n    Required Plugins:<br />\r\n    <ul>\r\n      <li>jqplot.canvasTextRenderer.m" +
"in.js</li>\r\n      <li>jqplot.canvasAxisTickRenderer.min.js</li>\r\n      <li>jqplo" +
"t.categoryAxisRenderer.min.js</li>\r\n    </ul>\r\n  </div>\r\n  <script type=\"text/ja" +
"vascript\">\r\n    $(document).ready(function () {\r\n\r\n      $.jqplot(\'non-numeric-a" +
"xis-values-graph\', ");


            
            #line 76 "..\..\Views\Core\_JQPlotNonNumericAxisValues.cshtml"
                                           Write(Html.Raw(Model[0].chartData.ToJson()));

            
            #line default
            #line hidden
WriteLiteral(", ");


            
            #line 76 "..\..\Views\Core\_JQPlotNonNumericAxisValues.cshtml"
                                                                                   Write(Html.Raw(Model[0].chartOptions.ToString()));

            
            #line default
            #line hidden
WriteLiteral(");\r\n    });\r\n  </script>\r\n</div>\r\n\r\n<div class=\"well ui-well\">\r\n  <h4>You could a" +
"lso have data as a date time series...</h4>\r\n  <pre><code>\r\n    object[][] data " +
"= new object[][] { \r\n      new object[] { \"01-Jan-2014\", 75 },\r\n      new object" +
"[] { \"01-Feb-2014\", 91 },\r\n      new object[] { \"27-Jun-2014\", 150 },\r\n      new" +
" object[] { \"17-July-2014\", 112 },\r\n      new object[] { \"22-Sep-2014\", 37 },\r\n " +
"     new object[] { \"08-Nov-2014\", 66 },\r\n      new object[] { \"11-Dec-2014\", 18" +
" }\r\n    };\r\n  </code></pre>\r\n</div>\r\n\r\n<div class=\"well ui-well\">\r\n  <h4>Then yo" +
"ur options would look something like these</h4>\r\n  <pre><code>\r\n  JQPlotOptions " +
"options = new JQPlotOptions\r\n  {\r\n    title = new TitleOptions(\"Date Data Render" +
"ing\"),\r\n    axes = new JQPlotAxes\r\n    {\r\n      xaxis = new JQPlot.SubOptions.Ax" +
"isOptions\r\n      {\r\n        <span class=\"comment\">// Note how we tell jqPlot tha" +
"t our X axis values are actually dates</span>\r\n        renderer = <span class=\"h" +
"ighlight\">EJQPlotRenderer.DateAxisRenderer</span>,     \r\n        tickOptions = n" +
"ew AxisTickRendererOptions\r\n        {\r\n          formatString = \"%b&nbsp;%#d\"\r\n " +
"       },\r\n        min = \"25-Dec-2013\"\r\n      }\r\n    }\r\n  };\r\n  </code></pre>\r\n<" +
"/div>\r\n\r\n<div class=\"well ui-well\">\r\n  <h4>And finally the output...</h4>\r\n  <di" +
"v class=\"content\">\r\n    <div id=\"date-graph\" class=\"graph\">\r\n    </div>\r\n    <br" +
" />\r\n    Required Plugins:<br />\r\n    <ul>\r\n      <li>jqplot.dateAxisRenderer.mi" +
"n.js</li>\r\n    </ul>\r\n  </div>\r\n  <script type=\"text/javascript\">\r\n    $(documen" +
"t).ready(function () {\r\n\r\n      $.jqplot(\'date-graph\', ");


            
            #line 133 "..\..\Views\Core\_JQPlotNonNumericAxisValues.cshtml"
                        Write(Html.Raw(Model[1].chartData.ToJson()));

            
            #line default
            #line hidden
WriteLiteral(", ");


            
            #line 133 "..\..\Views\Core\_JQPlotNonNumericAxisValues.cshtml"
                                                                Write(Html.Raw(Model[1].chartOptions.ToString()));

            
            #line default
            #line hidden
WriteLiteral(");\r\n    });\r\n  </script>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
