#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WebExtras.Core;
    using WebExtras.Mvc.Core;
    using WebExtras.Mvc.Html;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Core/_JQPlotLineGraph.cshtml")]
    public partial class _Views_Core__JQPlotLineGraph_cshtml : System.Web.Mvc.WebViewPage<WebExtras.JQPlot.JQPlotChartBase>
    {
        public _Views_Core__JQPlotLineGraph_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n<div class=\"well ui-well\">\r\n  <h4>Creating the jqPlot options</h4>\r\n  jqPlot gr" +
"aph options are created by instantiating the <strong>WebExtras.JQPlot.JQPlotOpti" +
"ons</strong> class.\r\n  <pre><code>\r\n  <span class=\"comment\">// Some basic option" +
"s are shown below</span>\r\n  JQPlotOptions options = new JQPlotOptions\r\n  {\r\n    " +
"title = new TitleOptions(\"Line Graph\")\r\n  };\r\n  </code></pre>\r\n</div>\r\n\r\n<div cl" +
"ass=\"well ui-well\">\r\n  <h4>Creating the graph data</h4>\r\n  jqPlot uses a 2 dimen" +
"sional numeric array for data. This can be of any numeric type <strong>int, deci" +
"mal, float or\r\n  double</strong>. In order to compensate for numerals WebExtras " +
"uses the biggest of the numeral types provided by .NET - \r\n  <strong>double</str" +
"ong>\r\n  <pre><code>\r\n  List&lt;double[]&gt; graphData = new List&lt;double[]&gt;" +
"();\r\n  \r\n  <span class=\"comment\">// Notice that each individual array added to t" +
"he \'graphData\' variable has 2 columns</span>\r\n  <span class=\"comment\">// The fir" +
"st column is your X co-ordinate and the second is your Y co-ordinate</span>\r\n\r\n " +
" graphData.Add(new double[] { 1, 5 });                            \r\n  graphData." +
"Add(new double[] { 2, 10 });\r\n\r\n  <span class=\"comment\">// ... and so on</span>\r" +
"\n  </code></pre>\r\n</div>\r\n\r\n<div class=\"well ui-well\">\r\n  <h4>Creating the jqPlo" +
"t Chart</h4>\r\n  All the things we have done so far now get bundled into a jqPlot" +
" chart by instantiating the <strong>WebExtras.JQPlot.JQPlotChart</strong> object" +
".\r\n  <pre><code>\r\n  <span class=\"comment\">// Notice that the <span class=\"highli" +
"ght\">chartData</span> property is a list, giving the flexibility of rendering mu" +
"ltiple data series in the same graph</span>\r\n  JQPlotChart chart = new JQPlotCha" +
"rt\r\n  {\r\n    chartData = new List&lt;double[][]&gt; { graphData.ToArray() },\r\n  " +
"  chartOptions = options\r\n  };\r\n  </code></pre>\r\n</div>\r\n\r\n<div class=\"well ui-w" +
"ell\">\r\n  <h4>Now in your HTML</h4>\r\n  Now that all C# bindings are done, it is t" +
"ime to render our graph. This can be done with a little bit of Javascript.\r\n  <p" +
"re><code>\r\n  ");


WriteLiteral("@model WebExtras.JQPlot.JQPlotChartBase\r\n  ....\r\n    ....\r\n    ....\r\n  <span clas" +
"s=\"comment\">// Note that unlike Flot where we specify the jQuery DIV element, he" +
"re we specify only the HTML ID of the DIV tag</span>\r\n  $.jqplot(\'line-graph\', ");


WriteLiteral("@Html.Raw(Model.chartData.ToJson()), ");


WriteLiteral(@"@Html.Raw(Model.chartOptions.ToString()));
  </code></pre>
</div>

<div class=""well ui-well"">
  <h4>And finally the output...</h4>
  <div class=""content"">
    <div id=""line-graph"" class=""graph"">
    </div>
  </div>
  <script type=""text/javascript"">
    $(document).ready(function () {

      $.jqplot('line-graph', ");


            
            #line 68 "..\..\Views\Core\_JQPlotLineGraph.cshtml"
                        Write(Html.Raw(Model.chartData.ToJson()));

            
            #line default
            #line hidden
WriteLiteral(", ");


            
            #line 68 "..\..\Views\Core\_JQPlotLineGraph.cshtml"
                                                             Write(Html.Raw(Model.chartOptions.ToString()));

            
            #line default
            #line hidden
WriteLiteral(");\r\n    });\r\n  </script>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
