#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WebExtras.Core;
    using WebExtras.Mvc.Core;
    using WebExtras.Mvc.Html;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Core/_PieGraph.cshtml")]
    public partial class _Views_Core__PieGraph_cshtml : System.Web.Mvc.WebViewPage<WebExtras.JQFlot.FlotChart>
    {
        public _Views_Core__PieGraph_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n<p>\r\n  In order to draw <strong>pie graphs</strong> you need <strong>jquery.flo" +
"t.pie.js</strong> i.e the\r\n  pie graph plugin.\r\n</p>\r\n\r\n<div class=\"well ui-well" +
"\">\r\n  <h4>Slightly modifying our series and options we get...</h4>\r\n  <pre><code" +
">\r\n  FlotSeries serie1 = new FlotSeries\r\n  {\r\n    label = \"Serie1\",\r\n    data = " +
"24.2658                    <span class=\"comment\">// Note that this is a single d" +
"ouble value as opposed to an 2d array</span>    \r\n  };\r\n  FlotSeries serie2 = ne" +
"w FlotSeries\r\n  {\r\n    label = \"Serie2\",\r\n    data = 86.1                       " +
"<span class=\"comment\">// Note that this is a single double value as opposed to a" +
"n 2d array</span>    \r\n  };\r\n  FlotSeries serie3 = new FlotSeries\r\n  {\r\n    labe" +
"l = \"Serie3\",\r\n    data = 91.0254                    <span class=\"comment\">// No" +
"te that this is a single double value as opposed to an 2d array</span>    \r\n  };" +
"\r\n\r\n  <span class=\"comment\">// Since we are drawing a pie we must supply each sl" +
"ice as a separate serie</span>\r\n  FlotSeries[] series = new FlotSeries[] { serie" +
"1, serie2, serie3 };\r\n\r\n  FlotOptions options = new FlotOptions\r\n  {\r\n    series" +
" = new SeriesOptions\r\n    {\r\n      pie = new PieGraph { show = true }    <span c" +
"lass=\"comment\">// This will denote that you want a Pie graph</span>\r\n    }\r\n  }\r" +
"\n  </code></pre>\r\n</div>\r\n\r\n<div class=\"well ui-well\">\r\n  <h4>And we have a pie " +
"graph...</h4>\r\n  <div class=\"content\">    \r\n    <div id=\"pie-graph\" class=\"pie-g" +
"raph\">\r\n    </div>\r\n  </div>\r\n\r\n  <script type=\"text/javascript\">\r\n    $(documen" +
"t).ready(function () {\r\n      $.plot($(\'#pie-graph\'), [");


            
            #line 49 "..\..\Views\Core\_PieGraph.cshtml"
                          Write(Html.Raw(string.Join(",", Model.chartSeries.Select(f => f.ToString()))));

            
            #line default
            #line hidden
WriteLiteral("], ");


            
            #line 49 "..\..\Views\Core\_PieGraph.cshtml"
                                                                                                     Write(Html.Raw(Model.chartOptions.ToString()));

            
            #line default
            #line hidden
WriteLiteral(");    \r\n    });\r\n  </script>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
