#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WebExtras.Core;
    using WebExtras.Mvc.Core;
    using WebExtras.Mvc.Html;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Core/_PostbackResult.cshtml")]
    public partial class _Views_Core__PostbackResult_cshtml : System.Web.Mvc.WebViewPage<WebExtras.DemoApp.Models.Core.DatatablesViewModel>
    {
        public _Views_Core__PostbackResult_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n<div class=\"well ui-well\">\r\n  <h4>That\'s our basic setup table again</h4>\r\n  <d" +
"iv class=\"output\">\r\n    ");


            
            #line 6 "..\..\Views\Core\_PostbackResult.cshtml"
Write(Html.Partial(MVC.Shared.Views._Datatable, Model.Table));

            
            #line default
            #line hidden
WriteLiteral("\r\n  </div>\r\n</div>\r\n\r\n<div class=\"well ui-well\">\r\n  <h4>And here is our searched/" +
"filtered result</h4>\r\n  <div class=\"output\">\r\n    ");


            
            #line 13 "..\..\Views\Core\_PostbackResult.cshtml"
Write(Html.Partial(MVC.Shared.Views._Datatable, Model.PostbackEnabledTable));

            
            #line default
            #line hidden
WriteLiteral("\r\n  </div>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
