#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Core/_StatusSetup.cshtml")]
    public partial class _Views_Core__StatusSetup_cshtml : System.Web.Mvc.WebViewPage<WebExtras.JQDataTables.Datatable>
    {
        public _Views_Core__StatusSetup_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n<p>\r\n  Status column is a column which contains the CSS classes to be applied t" +
"o the associated row. This feature is\r\n  very handy to notify the user of any st" +
"atus per row in the table. By default the four classes: error, warning, info and" +
"\r\n  success are supported which are analogous to the jQuery UI and Twitter Boots" +
"trap frameworks. However, since it is all\r\n  in the CSS, you are free to modify " +
"and use any classes of you choosing.\r\n</p>\r\n\r\n<div class=\"well ui-well\">\r\n  <h4>" +
"Modified Datatable constructor setup</h4>\r\n  We enable the <strong>enableStatusC" +
"olumn</strong> flag on the Datatable constructor\r\n  <pre><code>   \r\n  Datatable " +
"dTable = new Datatable(\"status-table\", dtSettings, dtRecords, enableStatusColumn" +
": true);\r\n  </code></pre>\r\n</div>\r\n\r\n<div class=\"well ui-well\">\r\n  <h4>Making th" +
"e data to be displayed</h4>\r\n  Now when making the data to be displayed you can " +
"add an extra column containing any CSS classes that you would\r\n  like to be used" +
" to add styling to the table rows.\r\n  <pre><code>   \r\n  string[][] dtData = new " +
"string[][]\r\n  {\r\n    new string[] { \"first column row 1\", \"second column row 1\"," +
" \"error\" },    \r\n    new string[] { \"first column row 2\", \"second column row 2\"," +
" \"warning\" },\r\n    new string[] { \"first column row 3\", \"second column row 3\", \"" +
"info\" },\r\n    new string[] { \"first column row 4\", \"second column row 4\", \"succe" +
"ss\" }\r\n  };\r\n  </code></pre>\r\n</div>\r\n\r\n<div class=\"well ui-well\">\r\n  <h4>Modifi" +
"ed Datatable constructor setup</h4>\r\n  We enable the <strong>enableStatusColumn<" +
"/strong> flag on the Datatable constructor\r\n  <pre><code>   \r\n  Datatable dTable" +
" = new Datatable(\"status-table\", dtSettings, dtRecords, enableStatusColumn: true" +
");\r\n  </code></pre>\r\n</div>\r\n\r\n<div class=\"well ui-well\">\r\n  <h4>And our status " +
"column enabled output is</h4>\r\n  <div class=\"output\">\r\n    ");


            
            #line 44 "..\..\Views\Core\_StatusSetup.cshtml"
Write(Html.Partial(MVC.Shared.Views._Datatable, Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n  </div>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
