#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WebExtras.Core;
    using WebExtras.Mvc.Core;
    using WebExtras.Mvc.Html;
    using WebExtras.Mvc.JQueryUI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/JQueryUI/Views/Home/Download.cshtml")]
    public partial class _Areas_JQueryUI_Views_Home_Download_cshtml : System.Web.Mvc.WebViewPage<string>
    {
        public _Areas_JQueryUI_Views_Home_Download_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Areas\JQueryUI\Views\Home\Download.cshtml"
  
    ViewBag.Title = "Download";


            
            #line default
            #line hidden
WriteLiteral("\r\n<h3 class=\"keep-center\">Download</h3>\r\n\r\n<div id=\"download-links\" class=\"col-gr" +
"oup keep-center\">\r\n  ");


            
            #line 10 "..\..\Areas\JQueryUI\Views\Home\Download.cshtml"
Write(Html.Button(EButton.Regular, "Stable<small> (" + Model + ")</small>", "http://webextras.codeplex.com/releases", true).AddIcon(EJQueryUIIcon.Circle_Arrow_S));

            
            #line default
            #line hidden
WriteLiteral("\r\n  \r\n  &nbsp;&nbsp;&nbsp;\r\n  \r\n  ");


            
            #line 14 "..\..\Areas\JQueryUI\Views\Home\Download.cshtml"
Write(Html.Button(EButton.Regular, "Nightly", "http://mihirmone.entrydns.org/app-downloads/webextras/webextras-nightly.zip", true).AddIcon(EJQueryUIIcon.Circle_Arrow_S).AddCssClass("ui-state-highlight"));

            
            #line default
            #line hidden
WriteLiteral("\r\n  \r\n  &nbsp;&nbsp;&nbsp;\r\n  \r\n  ");


            
            #line 18 "..\..\Areas\JQueryUI\Views\Home\Download.cshtml"
Write(Html.Button(EButton.Regular, "NuGet Gallery", "https://www.nuget.org/packages?q=webextras", true).AddIcon(EJQueryUIIcon.Circle_Arrow_S).AddCssClass("ui-state-highlight"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n</div>\r\n<br />\r\n<div class=\"col-group\">\r\n  <div class=\"col-12 changelog\">\r\n  " +
"  ");


            
            #line 24 "..\..\Areas\JQueryUI\Views\Home\Download.cshtml"
Write(Html.Inline(Links.Content.inline.changelog_html));

            
            #line default
            #line hidden
WriteLiteral("\r\n  </div>\r\n</div>\r\n<br />\r\n<script type=\"text/javascript\">\r\n  $(function () {\r\n " +
"   $(\'.changelog\').jScrollPane();\r\n    $(\'#download-links button\').button();\r\n  " +
"});\r\n</script>");


        }
    }
}
#pragma warning restore 1591
