
#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
    using SquishIt.Framework;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
    using SquishIt.Mvc;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
    using WebExtras.Core;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
    using WebExtras.DemoApp.App_Start;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
    using WebExtras.Mvc.Bootstrap;
    
    #line default
    #line hidden
    using WebExtras.Mvc.Bootstrap.v3;
    
    #line 5 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
    using WebExtras.Mvc.Core;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
    using WebExtras.Mvc.Html;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Bootstrap3/Views/Shared/_Layout.cshtml")]
    public partial class _Areas_Bootstrap3_Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Bootstrap3_Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {







WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n  <title>");


            
            #line 11 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
    Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(@" - Bootstrap 3 - WebExtras</title>
  <meta http-equiv=""Content-Type"" content=""text/html; charset=UTF-8"">
  <meta name=""viewport"" content=""width=device-width"" />
  <meta name=""author"" content=""Mihir Mone"" />
  <meta name=""application-name"" content=""WebExtras"" />
  <meta name=""description"" content="".net mvc, .net mvc 4, .net mvc helpers, bootstrap, flot, datatables, gumby"" />
  <link rel=""icon"" type=""image/ico"" href=""");


            
            #line 17 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
                                     Write(Links.Content.favicon_ico);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n  ");


            
            #line 18 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
Write(Bundle.Css().MvcRenderCachedAssetTag(ContentBundle.CSSBootstrap3.GetStringValue()));

            
            #line default
            #line hidden
WriteLiteral("\r\n  ");


            
            #line 19 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
Write(Bundle.JavaScript().MvcRenderCachedAssetTag(ContentBundle.JSBase.GetStringValue()));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n  <!--[if lt IE 9]><script language=\"javascript\" type=\"text/javascript\" src=\"" +
"");


            
            #line 21 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
                                                                        Write(Links.Scripts.excanvas_min_js);

            
            #line default
            #line hidden
WriteLiteral("\"></script><![endif]-->\r\n  \r\n  ");


            
            #line 23 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
Write(Bundle.JavaScript().MvcRenderCachedAssetTag(ContentBundle.JSBootstrap3.GetStringValue()));

            
            #line default
            #line hidden
WriteLiteral("\r\n  \r\n  ");


            
            #line 25 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral(@"

  <script type=""text/javascript"">
    function goToGoogle() { window.location = ""http://www.google.com.au""; }
    function goToYoutube() { window.location = ""http://www.youtube.com""; }
    function gotoCodeplex() { window.open('http://webextras.codeplex.com/releases', '_blank'); }
    function gotoDownload() { window.open('");


            
            #line 31 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
                                      Write(Url.Action(MVC.Bootstrap3.Home.Download()));

            
            #line default
            #line hidden
WriteLiteral("\', \'_self\'); }\r\n  </script>\r\n</head>\r\n<body>\r\n  <br />\r\n  <div class=\"navbar navb" +
"ar-inverse navbar-fixed-top\" role=\"navigation\">\r\n    <div class=\"collapse navbar" +
"-collapse\">\r\n      ");


            
            #line 38 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
 Write(Html.Hyperlink("WebExtras", Url.Content("~/")).AddCssClass("navbar-brand"));

            
            #line default
            #line hidden
WriteLiteral("\r\n      <ul class=\"nav navbar-nav\">\r\n        <li class=\"");


            
            #line 40 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
              Write(Html.SelectedTab("Home", "Index"));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 40 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
                                                  Write(Html.ActionLink("Home", MVC.Bootstrap3.Home.Index()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n        <li class=\"");


            
            #line 41 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
              Write(Html.SelectedTab("Core", "Generic"));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 41 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
                                                    Write(Html.ActionLink("Core", MVC.Bootstrap3.Core.Generic()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n        <li class=\"");


            
            #line 42 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
              Write(Html.SelectedTab("Core", "Datatables"));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 42 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
                                                       Write(Html.ActionLink("jQuery Datatables", MVC.Bootstrap3.Core.Datatables()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n        <li class=\"");


            
            #line 43 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
              Write(Html.SelectedTab("Core", new[] { "Flot", "JQPlot" }));

            
            #line default
            #line hidden
WriteLiteral(" dropdown\">\r\n          <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"" +
">Graphs<i class=\"caret\"></i></a>\r\n          <ul class=\"dropdown-menu\">\r\n        " +
"    <li>");


            
            #line 46 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
           Write(Html.Hyperlink("jQuery Flot", MVC.Bootstrap3.Core.Flot()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n            <li>");


            
            #line 47 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
           Write(Html.Hyperlink("jqPlot", MVC.Bootstrap3.Core.JQPlot()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n          </ul>\r\n        </li>\r\n        <li class=\"");


            
            #line 50 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
              Write(Html.SelectedTab("Mvc", new[] { "CoreHtml", "CoreForm" }));

            
            #line default
            #line hidden
WriteLiteral(" dropdown\">\r\n          <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"" +
">Mvc Core<i class=\"caret\"></i></a>\r\n          <ul class=\"dropdown-menu\">\r\n      " +
"      <li>");


            
            #line 53 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
           Write(Html.ActionLink("Custom Action Results", MVC.Bootstrap3.Mvc.ActionResults()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n            <li>");


            
            #line 54 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
           Write(Html.ActionLink("Html extensions", MVC.Bootstrap3.Mvc.CoreHtml()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n            <li>");


            
            #line 55 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
           Write(Html.ActionLink("Form extensions", MVC.Bootstrap3.Mvc.CoreForm()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n          </ul>\r\n        </li>\r\n        <li class=\"");


            
            #line 58 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
              Write(Html.SelectedTab("Mvc", new[] { "BootstrapHtml", "BootstrapForm" }));

            
            #line default
            #line hidden
WriteLiteral(" dropdown\">\r\n          <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"" +
">Mvc Bootstrap<i class=\"caret\"></i></a>\r\n          <ul class=\"dropdown-menu\">\r\n " +
"           <li>");


            
            #line 61 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
           Write(Html.ActionLink("Html extensions", MVC.Bootstrap3.Mvc.BootstrapHtml()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n            <li>");


            
            #line 62 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
           Write(Html.ActionLink("Form extensions", MVC.Bootstrap3.Mvc.BootstrapForm()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n          </ul>\r\n        </li>\r\n      </ul>\r\n      <ul class=\"nav navbar-n" +
"av navbar-right\">\r\n        <li>");


            
            #line 67 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
        Write(Html.Button(EButton.Regular, "Get WebExtras", "gotoDownload()")
                .AddCssClass("download-btn")
                .AsButton(EBootstrapButton.Primary)
                .AddIcon(EFontAwesomeIcon.Download));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n      </ul>\r\n    </div>\r\n  </div>\r\n  <div class=\"container main\">\r\n    ");


            
            #line 75 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden

            
            #line 75 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
                 WriteLiteral("\r\n  </div>\r\n  <footer>\r\n    <span style=\"float: left\" id=\"build-date\">");

            
            #line default
            #line hidden
            
            #line 78 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
                                                 Html.RenderAction(MVC.Flavour.BuildDetails()); 
            
            #line default
            #line hidden
WriteLiteral("</span>\r\n    <span style=\"float: right\">Copyright &copy; ");


            
            #line 79 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
                                           Write(DateTime.Now.Year);

            
            #line default
            #line hidden

            
            #line 79 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
                                                                  WriteLiteral(" Mihir Mone. All Rights Reserved.</span>\r\n    <div>");

            
            #line default
            #line hidden
            
            #line 80 "..\..\Areas\Bootstrap3\Views\Shared\_Layout.cshtml"
            Html.RenderAction(MVC.Flavour.VersionDetails()); 
            
            #line default
            #line hidden
WriteLiteral("</div>\r\n  </footer>\r\n</body>\r\n</html>");


        }
    }
}
#pragma warning restore 1591
