
using WebExtras.Gumby;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WebExtras.Core;
    using WebExtras.Mvc.Core;
    using WebExtras.Mvc.Gumby;
    using WebExtras.Mvc.Html;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Gumby/Views/Mvc/GumbyForm.cshtml")]
    public partial class _Areas_Gumby_Views_Mvc_GumbyForm_cshtml : System.Web.Mvc.WebViewPage<WebExtras.DemoApp.Models.Mvc.CoreFormViewModel>
    {
        public _Areas_Gumby_Views_Mvc_GumbyForm_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Areas\Gumby\Views\Mvc\GumbyForm.cshtml"
  
  ViewBag.Title = "Mvc Gumby Form Helper Extensions";


            
            #line default
            #line hidden
WriteLiteral(@"
<h3 class=""keep-center"">Mvc Gumby Form Helper Extensions</h3>

<div class=""row"">
  <div class=""six columns"">
    <div class=""row"">
      <div class=""three columns"">
        <strong>Assembly</strong>
      </div>
      <div class=""four columns"">
        WebExtras.Mvc.dll
      </div>
    </div>
    <div class=""row"">
      <div class=""three columns"">
        <strong>Namespace</strong>
      </div>
      <div class=""four columns"">
        WebExtras.Mvc.Gumby
      </div>
    </div>
  </div>
  <div class=""six columns"">
    <div class=""three columns"">
      <strong>Dependancies</strong>
    </div>
    <div class=""six columns"">
      <ul class=""dependancies"">
        <li>Appropriate third party libraries</li>
        <li>Gumby 2.5.x</li>
        <li>webextras.gumby.css</li>
      </ul>
    </div>
  </div>
</div>

<div class=""well"">
  <h4>Creating special buttons</h4>
  <p>Special buttons can be created by decorating hyperlinks and basic buttons with the appropriate special button type</p>

  <p>Markup</p>
  <pre><code>
  ");


WriteLiteral("@Html.Hyperlink(\"Take me to google\", \"http://www.google.com\")\r\n    .AsButton(EGum" +
"byButton.Default)\r\n  ");


WriteLiteral("@Html.Button(EButton.Regular, \"Take me to google\", \"window.location=\'http://www.g" +
"oogle.com.au\'\")\r\n    .AsButton(EGumbyButton.Info, EGumbyButtonStyle.Large)\r\n  </" +
"code></pre>\r\n");


            
            #line 53 "..\..\Areas\Gumby\Views\Mvc\GumbyForm.cshtml"
     
    const string msg = "You can create a button of type <strong>EButton.Cancel</strong> which takes you back to the previous page. When a button of this" +
                       "type is created, any onclick event specified will be blatantly ignored.";
  

            
            #line default
            #line hidden
WriteLiteral("  ");


            
            #line 57 "..\..\Areas\Gumby\Views\Mvc\GumbyForm.cshtml"
Write(Html.Alert(EMessage.Warning, msg, string.Empty, EGumbyIcon.Flag));

            
            #line default
            #line hidden
WriteLiteral("\r\n  <p>Output</p>\r\n  <div class=\"content\">\r\n    <p>\r\n      ");


            
            #line 61 "..\..\Areas\Gumby\Views\Mvc\GumbyForm.cshtml"
 Write(Html.Hyperlink("Take me to google", "http://www.google.com").AsButton(EGumbyButton.Default));

            
            #line default
            #line hidden
WriteLiteral("\r\n      ");


            
            #line 62 "..\..\Areas\Gumby\Views\Mvc\GumbyForm.cshtml"
 Write(Html.Hyperlink("Take me to google", "http://www.google.com").AsButton(EGumbyButton.Primary));

            
            #line default
            #line hidden
WriteLiteral("\r\n      ");


            
            #line 63 "..\..\Areas\Gumby\Views\Mvc\GumbyForm.cshtml"
 Write(Html.Button(EButton.Cancel, "Take me back").AsButton(EGumbyButton.Danger));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n    <p>\r\n      ");


            
            #line 66 "..\..\Areas\Gumby\Views\Mvc\GumbyForm.cshtml"
 Write(Html.Hyperlink("Take me to google", "http://www.google.com").AsButton(EGumbyButton.Info, EGumbyButtonStyle.Large));

            
            #line default
            #line hidden
WriteLiteral("\r\n      ");


            
            #line 67 "..\..\Areas\Gumby\Views\Mvc\GumbyForm.cshtml"
 Write(Html.Hyperlink("Take me to google", "http://www.google.com").AsButton(EGumbyButton.Warning, EGumbyButtonStyle.Oval));

            
            #line default
            #line hidden
WriteLiteral("\r\n      ");


            
            #line 68 "..\..\Areas\Gumby\Views\Mvc\GumbyForm.cshtml"
 Write(Html.Button(EButton.Regular, "Take me to google", "goToGoogle()").AsButton(EGumbyButton.Secondary, EGumbyButtonStyle.Pill_Left));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n  </div>\r\n  <p>All available extensions</p>\r\n  <pre><code>\r\n  .AsButt" +
"on(type)\r\n  .AsButton(type, size/style)\r\n  </code></pre>\r\n  ");


            
            #line 76 "..\..\Areas\Gumby\Views\Mvc\GumbyForm.cshtml"
Write(Html.Alert(EMessage.Warning, "Note that this extension can only be used for hyperlinks and button elements", string.Empty, EGumbyIcon.Flag));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>");


        }
    }
}
#pragma warning restore 1591
