#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WebExtras.Core;
    using WebExtras.Mvc.Bootstrap;
    using WebExtras.Mvc.Bootstrap.v2;
    using WebExtras.Mvc.Core;
    using WebExtras.Mvc.Html;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Bootstrap/Views/Mvc/ActionResults.cshtml")]
    public partial class _Areas_Bootstrap_Views_Mvc_ActionResults_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Bootstrap_Views_Mvc_ActionResults_cshtml()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Areas\Bootstrap\Views\Mvc\ActionResults.cshtml"
  
  ViewBag.Title = "ActionResults";


            
            #line default
            #line hidden
WriteLiteral(@"
<h3 class=""keep-center"">Extra Action Results</h3>

<div class=""row-fluid"">
  <div class=""span6"">
    <div class=""row-fluid"">
      <div class=""span3"">
        <strong>Assembly</strong>
      </div>
      <div class=""span4"">
        WebExtras.Mvc.dll
      </div>
    </div>
    <div class=""row-fluid"">
      <div class=""span3"">
        <strong>Namespace</strong>
      </div>
      <div class=""span4"">
        WebExtras.Mvc.Core
      </div>
    </div>
  </div>
</div>

");


            
            #line 28 "..\..\Areas\Bootstrap\Views\Mvc\ActionResults.cshtml"
Write(Html.Partial(MVC.Mvc.Views._JsonNetResult));

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
