#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WebExtras.Core;
    using WebExtras.Mvc.Core;
    using WebExtras.Mvc.Html;
    using WebExtras.Mvc.JQueryUI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/JQueryUI/Views/Mvc/JQueryUIForm.cshtml")]
    public partial class _Areas_JQueryUI_Views_Mvc_JQueryUIForm_cshtml : System.Web.Mvc.WebViewPage<WebExtras.DemoApp.Models.Mvc.CoreFormViewModel>
    {
        public _Areas_JQueryUI_Views_Mvc_JQueryUIForm_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Areas\JQueryUI\Views\Mvc\JQueryUIForm.cshtml"
  
  ViewBag.Title = "Mvc JQuery UI Form Helper Extensions";


            
            #line default
            #line hidden
WriteLiteral(@"
<h3 class=""keep-center"">Mvc Form Helper Extensions</h3>

<div class=""col-group"">
  <div class=""col-6"">
    <div class=""col-12"">
      <div class=""col-3"">
        <strong>Assembly</strong>
      </div>
      <div class=""col-4"">
        WebExtras.Mvc.dll
      </div>
    </div>
    <div class=""col-12"">
      <div class=""col-3"">
        <strong>Namespace</strong>
      </div>
      <div class=""col-4"">
        WebExtras.Mvc.Core
      </div>
    </div>
  </div>
  <div class=""col-offset-6"">
    <div class=""col-4"">
      <strong>Dependancies</strong>
    </div>
    <div class=""col-6"">
      <ul class=""dependancies"">
        <li>Appropriate third party libraries</li>
        <li>webextras.jqueryui.css</li>
      </ul>
    </div>
  </div>
</div>

<div class=""ui-well"">
  <h4>Date time pickers</h4>
  <p>
    WebExtras provides helper methods for rendering a date time picker attached to a textbox by using a 
    great little date time picker provided by Trent Richarson. You can get a copy of the date time picker from 
    ");


            
            #line 46 "..\..\Areas\JQueryUI\Views\Mvc\JQueryUIForm.cshtml"
Write(Html.Hyperlink("here", "http://trentrichardson.com/examples/timepicker/", new { target = "_blank" }));

            
            #line default
            #line hidden
WriteLiteral(".\r\n  </p>\r\n  <p>Markup</p>\r\n  <pre><code>\r\n<span class=\"comment\">// By default da" +
"te format is \'yy-mm-dd\' (in JS) == \'yyyy-MM-dd\' (in C#)</span>\r\n");


WriteLiteral("@Html.DateTextBoxFor(f => f.DateTextBox, \r\n    new { showOn = \"button\", buttonIma" +
"ge = \"/content/calendar.gif\", buttonImageOnly = true })\r\n    \r\n<span class=\"comm" +
"ent\">// By default time format is \'hh:mm\' (in JS) == \'hh:mm\' (in C#)</span>\r\n");


WriteLiteral("@Html.TimeTextBoxFor(f => f.TimeTextBox)\r\n    \r\n<span class=\"comment\">// By defau" +
"lt date time format is \'yy-mm-dd hh:mm\' (in JS) == \'yyyy-MM-dd hh:mm\' (in C#)</s" +
"pan>\r\n");


WriteLiteral(@"@Html.DateTimeTextBoxFor(f => f.DateTimeTextBox, 
    new { showOn = ""button"", buttonImage = ""/content/calendar.gif"", buttonImageOnly = true })
  </code></pre>
  <p>Output</p>
  <div class=""col-group keep-center"">
    <div class=""col-3"">
      <div class=""content"">
        <p>Date only picker</p>
        
        ");


            
            #line 67 "..\..\Areas\JQueryUI\Views\Mvc\JQueryUIForm.cshtml"
   Write(Html.DateTextBoxFor(f => f.DateTextBox, new
        {
          showOn = "button",
          buttonImage = "/content/img/calendar.gif",
          buttonImageOnly = true
        }));

            
            #line default
            #line hidden
WriteLiteral("\r\n      </div>\r\n    </div>\r\n    <div class=\"col-3 col-offset-1\">\r\n      <div clas" +
"s=\"content\">\r\n        <p>Time only picker</p>\r\n        \r\n        ");


            
            #line 79 "..\..\Areas\JQueryUI\Views\Mvc\JQueryUIForm.cshtml"
   Write(Html.TimeTextBoxFor(f => f.TimeTextBox));

            
            #line default
            #line hidden
WriteLiteral("\r\n      </div>\r\n    </div>\r\n    <div class=\"col-3 col-offset-1\">\r\n      <div clas" +
"s=\"content\">\r\n        <p>Date time picker</p>\r\n        \r\n        ");


            
            #line 86 "..\..\Areas\JQueryUI\Views\Mvc\JQueryUIForm.cshtml"
   Write(Html.DateTimeTextBoxFor(f => f.DateTimeTextBox, new
        {
          showOn = "button",
          buttonImage = "/content/img/calendar.gif",
          buttonImageOnly = true
        }));

            
            #line default
            #line hidden
WriteLiteral("\r\n      </div>\r\n    </div>\r\n  </div>\r\n\r\n</div>\r\n\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
