/*
* This file is part of - WebExtras
* Copyright (C) 2013 Mihir Mone
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Lesser General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Lesser General Public License for more details.
*
* You should have received a copy of the GNU Lesser General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#pragma warning disable 1591

using System;
using WebExtras.Core;

namespace WebExtras.Mvc.Bootstrap
{
  /// <summary>
  /// A collection of all available icons
  /// </summary>
  [Serializable]
  public enum BootstrapIcon
  {
    Adjust,
    Align_Center,
    Align_Justify,
    Align_Left,
    Align_Right,
    Arrow_Down,
    Arrow_Left,
    Arrow_Right,
    Arrow_Up,
    Asterisk,
    Backward,
    Ban_Circle,
    Barcode,
    Bell,
    Bold,
    Book,
    Bookmark,
    Briefcase,
    Bullhorn,
    Calendar,
    Camera,
    Certificate,
    Check,
    Chevron_Down,
    Chevron_Left,
    Chevron_Right,
    Chevron_Up,
    Circle_Arrow_Down,
    Circle_Arrow_Left,
    Circle_Arrow_Right,
    Circle_Arrow_Up,
    Cog,
    Comment,
    Download,
    Download_Alt,
    Edit,
    Eject,
    Envelope,
    Exclamation_Sign,
    Eye_Close,
    Eye_Open,
    Facetime_Video,
    Fast_Backward,
    Fast_Forward,
    File,
    Film,
    Filter,
    Fire,
    Flag,
    Folder_Close,
    Folder_Open,
    Font,
    Forward,
    Fullscreen,
    Gift,
    Glass,
    Globe,
    Hand_Down,
    Hand_Left,
    Hand_Right,
    Hand_Up,
    Hdd,
    Headphones,
    Heart,
    Home,
    Inbox,
    Indent_Left,
    Indent_Right,
    Info_Sign,
    Italic,
    Leaf,
    List,
    List_Alt,
    Lock,
    Magnet,
    Map_Marker,
    Minus,
    Minus_Sign,
    Move,
    Music,
    Off,
    Ok,
    Ok_Circle,
    Ok_Sign,
    Pause,
    Pencil,
    Picture,
    Plane,
    Play,
    Play_Circle,
    Plus,
    Plus_Sign,
    Print,
    Qrcode,
    Question_Sign,
    Random,
    Refresh,
    Remove,
    Remove_Circle,
    Remove_Sign,
    Repeat,
    Resize_Full,
    Resize_Horizontal,
    Resize_Small,
    Resize_Vertical,
    Road,
    Screenshot,
    Search,
    Share,
    Share_Alt,
    Shopping_Cart,
    Signal,
    Star,
    Star_Empty,
    Step_Backward,
    Step_Forward,
    Stop,
    Tag,
    Tags,
    Tasks,
    Text_Height,
    Text_Width,
    Th,
    Th_Large,
    Th_List,
    Thumbs_Down,
    Thumbs_Up,
    Time,
    Tint,
    Trash,
    Upload,
    User,
    Volume_Down,
    Volume_Off,
    Volume_Up,
    Warning_Sign,
    Wrench,
    Zoom_In,
    Zoom_Out,
  }
}
