#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WebExtras.Core;
    using WebExtras.Mvc.Bootstrap;
    using WebExtras.Mvc.Bootstrap.v3;
    using WebExtras.Mvc.Core;
    using WebExtras.Mvc.Html;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Bootstrap3/Views/Home/Download.cshtml")]
    public partial class _Areas_Bootstrap3_Views_Home_Download_cshtml : System.Web.Mvc.WebViewPage<string>
    {
        public _Areas_Bootstrap3_Views_Home_Download_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Areas\Bootstrap3\Views\Home\Download.cshtml"
  
  ViewBag.Title = "Download";


            
            #line default
            #line hidden
WriteLiteral("<h3 class=\"keep-center\">Downloads\r\n</h3>\r\n<div class=\"row-fluid\">\r\n  <div class=\"" +
"keep-center\">\r\n    ");


            
            #line 10 "..\..\Areas\Bootstrap3\Views\Home\Download.cshtml"
Write(Html.Hyperlink(" Stable<small> (" + Model + ")</small>", "http://webextras.codeplex.com/releases")
      .AsButton(EBootstrapButton.Success, EBootstrapButton.Large)
      .AddIcon(EFontAwesomeIcon.Download, EFontAwesomeIconSize.Large));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    &nbsp;&nbsp;&nbsp;\r\n\r\n    ");


            
            #line 16 "..\..\Areas\Bootstrap3\Views\Home\Download.cshtml"
Write(Html.Hyperlink(" Nightly", "http://mihirmone.entrydns.org/app-downloads/webextras/webextras-nightly.zip")
      .AsButton(EBootstrapButton.Default, EBootstrapButton.Large)
      .AddIcon(EFontAwesomeIcon.Download, EFontAwesomeIconSize.Large));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    &nbsp;&nbsp;&nbsp;\r\n\r\n    ");


            
            #line 22 "..\..\Areas\Bootstrap3\Views\Home\Download.cshtml"
Write(Html.Hyperlink(" NuGet Gallery", "https://www.nuget.org/packages?q=webextras")
      .AsButton(EBootstrapButton.Default, EBootstrapButton.Large)
      .AddIcon(EFontAwesomeIcon.Download, EFontAwesomeIconSize.Large));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <br />\r\n    ");


            
            #line 27 "..\..\Areas\Bootstrap3\Views\Home\Download.cshtml"
Write(Html.Hyperlink("Older versions", "javascript:gotoCodeplex()"));

            
            #line default
            #line hidden
WriteLiteral("\r\n  </div>\r\n</div>\r\n<br />\r\n<div class=\"row-fluid\">\r\n  <div class=\"span12 changel" +
"og\">\r\n    ");


            
            #line 33 "..\..\Areas\Bootstrap3\Views\Home\Download.cshtml"
Write(Html.Inline(Links.Content.inline.changelog_html));

            
            #line default
            #line hidden
WriteLiteral("\r\n  </div>\r\n</div>\r\n<br />\r\n<script type=\"text/javascript\">\r\n  $(function () {\r\n " +
"   $(\'.changelog\').jScrollPane();\r\n  });\r\n</script>\r\n");


        }
    }
}
#pragma warning restore 1591
