#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WebExtras.Core;
    using WebExtras.Mvc.Core;
    using WebExtras.Mvc.Gumby;
    using WebExtras.Mvc.Html;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Gumby/Views/Core/Generic.cshtml")]
    public partial class _Areas_Gumby_Views_Core_Generic_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Gumby_Views_Core_Generic_cshtml()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Areas\Gumby\Views\Core\Generic.cshtml"
  
  ViewBag.Title = "Generic .NET Extensions";


            
            #line default
            #line hidden
WriteLiteral(@"<h3 class=""keep-center"">Generic .NET Extensions and Helpers</h3>
<div class=""row"">
  <div class=""six columns"">
    <div class=""row"">
      <div class=""three columns"">
        <strong>Assembly</strong>
      </div>
      <div class=""three columns"">
        WebExtras.dll
      </div>
    </div>
    <div class=""row"">
      <div class=""three columns"">
        <strong>Namespace</strong>
      </div>
      <div class=""three columns"">
        WebExtras.Core
      </div>
    </div>
  </div>
</div>

");



WriteLiteral(@"
<div class=""well"">
  <h4>Object Extensions</h4>
  <p>
    WebExtras provides a general purpose object cloner which performs a deep clone of the given object.
    However, in order for the cloning to work, all objects (including any child object of the class) to 
    be cloned must be marked as serializable using the [Serializable] decorator attribute.
  </p>
  <p>Markup</p>
  <pre><code>
  SomeClass object1 = new SomeClass();
  SomeClass object2 = object1.DeepClone();
  </code></pre>
</div>

");



WriteLiteral("\r\n<div class=\"well\">\r\n  <h4>Enum Extensions</h4>\r\n  <p>WebExtras provides two enu" +
"m extension methods viz., ToTitleCase() and GetStringValue()</p>\r\n  <div class=\"" +
"row\">\r\n    <div class=\"six columns\">Consider the following C# enumeration</div>\r" +
"\n    <div class=\"six columns\">\r\n      ToTitleCase() as the method name suggests " +
"will convert the enum \r\n      value to it\'s titlecase representation based on th" +
"e current system culture\r\n    </div>    \r\n  </div>\r\n  <div class=\"row\">\r\n    <di" +
"v class=\"six columns\">\r\n      <pre><code>\r\n  <span class=\"comment\">// Enum defin" +
"ition</span>\r\n  public enum TestEnum\r\n  {\r\n    [StringValue(\"My great Enum\")]\r\n " +
"   enumvalue = 0,\r\n\r\n    [StringValue(typeof(MyCustomStringValueDecider))]\r\n    " +
"customEnumValue = 1\r\n  }\r\n    </code></pre>\r\n    </div>\r\n    <div class=\"six col" +
"umns\">\r\n      <pre><code>\r\n  <span class=\"comment\">// Invocation of ToTitleCase<" +
"/span>\r\n  TestEnum.enumvalue.ToTitleCase()\r\n\r\n  <span class=\"comment\">// Output<" +
"/span>\r\n  Enumvalue\r\n    </code></pre>\r\n    </div>    \r\n  </div>\r\n  <div class=\"" +
"row\">\r\n    <div class=\"twelve columns\">\r\n      GetStringValue() simply retrieves" +
" the string value decorated either using a static\r\n      text or by using a <spa" +
"n class=\"highlight\">IStringValueDecider</span> implementation of the StringValue" +
" attribute. \r\n      This is especially useful if you want an enum value to have " +
"an integer representation \r\n      as well as a string representation.\r\n    </div" +
">\r\n  </div>\r\n  <div class=\"row\">\r\n    <div class=\"six columns\">\r\n      <pre><cod" +
"e>\r\n  <span class=\"comment\">// Invocation of GetStringValue</span>\r\n  TestEnum.e" +
"numvalue.GetStringValue()\r\n\r\n  <span class=\"comment\">// Output</span>\r\n  My grea" +
"t Enum\r\n    </code></pre>\r\n    </div>\r\n    <div class=\"six columns\">\r\n      <pre" +
"><code>\r\n  <span class=\"comment\">// This is how MyCustomStringValueDecider class" +
" looks</span>\r\n  class MyCustomStringValueDecider : IStringValueDecider\r\n  {\r\n  " +
"  public string Decide()\r\n    {\r\n      <span class=\"comment\">// Let us say we ev" +
"aluated some condition here<br />      // and our result was \"my decided value\"<" +
"/span>\r\n      return \"my decided value\";\r\n    }\r\n  }\r\n\r\n  <span class=\"comment\">" +
"// Invocation of GetStringValue on a value that has a <br />  // custom string v" +
"alue decider</span>\r\n  TestEnum.customEnumValue.GetStringValue()\r\n\r\n  <span clas" +
"s=\"comment\">// Output</span>\r\n  my decided value\r\n    </code></pre>\r\n    </div>\r" +
"\n\r\n  </div>\r\n</div>\r\n\r\n");



WriteLiteral("\r\n<div class=\"well\">\r\n  <h4>String Extensions</h4>\r\n  <p>WebExtras provides two s" +
"tring extension methods viz., ToTitleCase() and ContainsIgnoreCase()</p>\r\n  <div" +
" class=\"row\">\r\n    <div class=\"four columns\">\r\n      ToTitleCase() as the method" +
" name suggests will convert the string \r\n      value to it\'s titlecase represent" +
"ation based on the current system culture\r\n    </div>\r\n    <div class=\"four colu" +
"mns\">\r\n      ContainsIgnoreCase() simply compares the current string with a give" +
"n string and\r\n      checks whether the current string contains the given string " +
"irrespective of case\r\n    </div>\r\n    <div class=\"four columns\">\r\n        Remove" +
"() method removes all occurences of the given string from it\'s parent string. Th" +
"is extension \r\n        simply uses the Replace() method internally but making us" +
"e of Remove() is semantically clearer.\r\n      </div>\r\n  </div>\r\n  <div class=\"ro" +
"w\">    \r\n    <div class=\"four columns\">\r\n      <pre><code>\r\n  <span class=\"comme" +
"nt\">// String definition</span>\r\n  string str = \"basic\"\r\n\r\n  <span class=\"commen" +
"t\">// Invocation of ToTitleCase</span>\r\n  str.ToTitleCase()\r\n\r\n  <span class=\"co" +
"mment\">// Output</span>\r\n  Basic\r\n    </code></pre>\r\n    </div>\r\n    <div class=" +
"\"four columns\">\r\n      <pre><code>\r\n  <span class=\"comment\">// String definition" +
"</span>\r\n  string str = \"basic\"\r\n\r\n  <span class=\"comment\">// Invocation of Cont" +
"ainsIgnoreCase</span>\r\n  str.ContainsIgnoreCase(\"BAS\")\r\n\r\n  <span class=\"comment" +
"\">// Output</span>\r\n  true\r\n    </code></pre>\r\n    </div>\r\n    <div class=\"four " +
"columns\">\r\n        <pre><code>\r\n  <span class=\"comment\">// String definition</sp" +
"an> \r\n  string str = \"basically basic\"\r\n\r\n  <span class=\"comment\">// Invocation " +
"of Remove</span> \r\n  str.Remove(\"bas\")\r\n            \r\n  <span class=\"comment\">//" +
" Output</span> \r\n  ically ic\r\n          </code></pre>\r\n      </div>\r\n  </div>\r\n<" +
"/div>\r\n\r\n");



WriteLiteral(@"
<div class=""well"">
  <h4>Double Extensions</h4>
  <p>WebExtras provides ability to convert JavaScript ticks to a .NET DateTime object by using the ToDateTime()
    extension method available to all double values
  </p>
  <pre><code>
  double ticks = 1356998400000;
  DateTime dt = ticks.ToDateTime();       <span class=""comment"">// Parsed date time is 01/01/2013 12:00:00 AM</span>
  </code></pre>
</div>

");



WriteLiteral(@"
<div class=""well"">
  <h4>DateTime Extensions</h4>
  <p>As with doubles, WebExtras also provides ability to convert a .NET DateTime object to it's equivalent
    JavaScript timestamp by using the ToJavaScriptDate() extension method available to all DateTime values
  </p>
  <pre><code>
  DateTime dt = DateTime.Parse(""2013-01-01 00:00:00"");
  double ticks = dt.ToJavaScriptDate();       <span class=""comment"">// Parsed JavaScript ticks are 1356998400000</span>
  </code></pre>
</div>

");



WriteLiteral(@"
<div class=""well"">
  <h4>JsFunc utility class</h4>
  <p>In order to create and return custom JavaScript functions for the DataTables and Flot hooks, WebExtras provides
    the <strong>WebExtras.Core.JsFunc</strong> class.
  </p>
  <p>Markup</p>
  <pre><code>
  JsFunc foo = new JsFunc
  {
    Name = ""foo"",
    ParameterNames = new string[] { ""myParam1"", ""myParam2"" },
    Body = ""alert(myParam1 + '...' + myParam2);"",
    OnDocumentReady = true
  };
  </code></pre>
  <p>And the serialised output will be</p>
  <pre><code>
  <span class=""comment"">// You MUST use the Json.NET serialiser in order to serialise properly</span>
  $(document).ready(function() {
    function foo(myParam1, myParam2) {
      alert(myParam1 + '...' + myParam2);
    };
  });
  </code></pre>
</div>");


        }
    }
}
#pragma warning restore 1591
