#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
    using SquishIt.Framework;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
    using SquishIt.Mvc;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
    using WebExtras.Core;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
    using WebExtras.DemoApp.App_Start;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
    using WebExtras.Mvc.Core;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
    using WebExtras.Mvc.Gumby;
    
    #line default
    #line hidden
    using WebExtras.Mvc.Html;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Gumby/Views/Shared/_Layout.cshtml")]
    public partial class _Areas_Gumby_Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Gumby_Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {






WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n  <title>");


            
            #line 10 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
    Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(@" - Gumby - WebExtras</title>
  <meta http-equiv=""Content-Type"" content=""text/html; charset=UTF-8"" />
  <meta name=""viewport"" content=""width=device-width"" />
  <meta name=""author"" content=""Mihir Mone"" />
  <meta name=""application-name"" content=""WebExtras"" />
  <meta name=""description"" content="".net mvc, .net mvc 4, .net mvc helpers, bootstrap, flot, datatables, gumby"" />
  <link rel=""icon"" type=""image/ico"" href=""");


            
            #line 16 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
                                     Write(Links.Content.favicon_ico);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n  ");


            
            #line 17 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
Write(Bundle.Css().MvcRenderCachedAssetTag(ContentBundle.CSSGumby.GetStringValue()));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n  <!--[if lt IE 9]><script language=\"javascript\" type=\"text/javascript\" src=\"" +
"");


            
            #line 19 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
                                                                        Write(Links.Scripts.excanvas_min_js);

            
            #line default
            #line hidden
WriteLiteral("\"></script><![endif]-->\r\n\r\n  ");


            
            #line 21 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
Write(Bundle.JavaScript().MvcRenderCachedAssetTag(ContentBundle.JSBase.GetStringValue()));

            
            #line default
            #line hidden
WriteLiteral("\r\n  ");


            
            #line 22 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
Write(Bundle.JavaScript().MvcRenderCachedAssetTag(ContentBundle.JSGumby.GetStringValue()));

            
            #line default
            #line hidden
WriteLiteral("\r\n  ");


            
            #line 23 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral(@"
  <script type=""text/javascript"">
    function goToGoogle() { window.location = ""http://www.google.com.au""; }
    function goToYoutube() { window.location = ""http://www.youtube.com""; }
    function gotoCodeplex() { window.open('http://webextras.codeplex.com/releases', '_blank'); }
  </script>
</head>
<body>
  <br />
  <div id=""navbar"" class=""row navbar metro"" gumby-fixed=""top"">
    <h4 class=""two columns logo"">
      ");


            
            #line 34 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
 Write(Html.Hyperlink("WebExtras", Url.Content("~/")));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </h4>\r\n    <ul class=\"ten columns\">\r\n      <li class=\"");


            
            #line 37 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
            Write(Html.SelectedTab("Home", "Index"));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 37 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
                                                Write(Html.Hyperlink("Home", MVC.Gumby.Home.Index()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n      <li class=\"");


            
            #line 38 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
            Write(Html.SelectedTab("Core", "Generic"));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 38 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
                                                  Write(Html.Hyperlink("Core", MVC.Gumby.Core.Index()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n      <li class=\"");


            
            #line 39 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
            Write(Html.SelectedTab("Core", "Datatables"));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 39 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
                                                     Write(Html.Hyperlink("jQuery Datatables", MVC.Gumby.Core.Datatables()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n      <li class=\"");


            
            #line 40 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
            Write(Html.SelectedTab("Core", new[] { "Flot", "JQPlot" }));

            
            #line default
            #line hidden
WriteLiteral(" dropdown\">");


            
            #line 40 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
                                                                            Write(Html.Hyperlink("Graphs", "#"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div class=\"dropdown\">\r\n          <ul>\r\n            <li>");


            
            #line 43 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
           Write(Html.Hyperlink("jQuery Flot", MVC.Gumby.Core.Flot()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n            <li>");


            
            #line 44 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
           Write(Html.Hyperlink("jqPlot", MVC.Gumby.Core.JQPlot()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n          </ul>\r\n        </div>\r\n      </li>\r\n      <li class=\"");


            
            #line 48 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
            Write(Html.SelectedTab("Mvc", new[] { "ActionResults", "CoreHtml", "CoreForm" }));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 48 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
                                                                                         Write(Html.Hyperlink("Mvc Core", "#"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div class=\"dropdown\">\r\n          <ul>\r\n            <li>");


            
            #line 51 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
           Write(Html.Hyperlink("Custom Action Results", MVC.Gumby.Mvc.ActionResults()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n            <li>");


            
            #line 52 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
           Write(Html.Hyperlink("Html Extensions", MVC.Gumby.Mvc.CoreHtml()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n            <li>");


            
            #line 53 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
           Write(Html.Hyperlink("Form Extensions", MVC.Gumby.Mvc.CoreForm()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n          </ul>\r\n        </div>\r\n      </li>\r\n      <li class=\"");


            
            #line 57 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
            Write(Html.SelectedTab("Mvc", new[] { "GumbyHtml", "GumbyForm" }));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 57 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
                                                                          Write(Html.Hyperlink("Mvc Gumby", "#"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div class=\"dropdown\">\r\n          <ul>\r\n            <li>");


            
            #line 60 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
           Write(Html.Hyperlink("Html Extensions", MVC.Gumby.Mvc.GumbyHtml()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n            <li>");


            
            #line 61 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
           Write(Html.Hyperlink("Form Extensions", MVC.Gumby.Mvc.GumbyForm()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n          </ul>\r\n        </div>\r\n      </li>\r\n      <li>\r\n        ");


            
            #line 66 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
    Write(Html.Hyperlink("Get WebExtras", MVC.Gumby.Home.Download())
        .AddIcon(EGumbyIcon.Download)
        .AsButton(EGumbyButton.Primary));

            
            #line default
            #line hidden
WriteLiteral("\r\n      </li>\r\n    </ul>\r\n  </div>\r\n  <div class=\"container main\">\r\n    ");


            
            #line 73 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden

            
            #line 73 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
                 WriteLiteral("\r\n  </div>\r\n  <footer>\r\n    <span style=\"float: left\" id=\"build-date\">");

            
            #line default
            #line hidden
            
            #line 76 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
                                                 Html.RenderAction(MVC.Flavour.BuildDetails()); 
            
            #line default
            #line hidden
WriteLiteral("</span>\r\n    <span style=\"float: right\">Copyright &copy; ");


            
            #line 77 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
                                           Write(DateTime.Now.Year);

            
            #line default
            #line hidden

            
            #line 77 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
                                                                  WriteLiteral(" Mihir Mone. All Rights Reserved.</span>\r\n    <div>");

            
            #line default
            #line hidden
            
            #line 78 "..\..\Areas\Gumby\Views\Shared\_Layout.cshtml"
            Html.RenderAction(MVC.Flavour.VersionDetails()); 
            
            #line default
            #line hidden
WriteLiteral("</div>\r\n  </footer>\r\n</body>\r\n</html>\r\n");


        }
    }
}
#pragma warning restore 1591
