// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class CoreController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _AjaxSetup = "_AjaxSetup";
                public readonly string _BasicSetup = "_BasicSetup";
                public readonly string _PagedSetup = "_PagedSetup";
                public readonly string _PostbackResult = "_PostbackResult";
                public readonly string _SortedSetup = "_SortedSetup";
                public readonly string _StatusSetup = "_StatusSetup";
            }
            public readonly string _AjaxSetup = "~/Views/Core/_AjaxSetup.cshtml";
            public readonly string _BasicSetup = "~/Views/Core/_BasicSetup.cshtml";
            public readonly string _PagedSetup = "~/Views/Core/_PagedSetup.cshtml";
            public readonly string _PostbackResult = "~/Views/Core/_PostbackResult.cshtml";
            public readonly string _SortedSetup = "~/Views/Core/_SortedSetup.cshtml";
            public readonly string _StatusSetup = "~/Views/Core/_StatusSetup.cshtml";
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
