// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class CoreController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _AjaxSetup = "_AjaxSetup";
                public readonly string _BarGraph = "_BarGraph";
                public readonly string _BasicSetup = "_BasicSetup";
                public readonly string _CurvedLineGraph = "_CurvedLineGraph";
                public readonly string _CustomFlotFormatters = "_CustomFlotFormatters";
                public readonly string _DashedGraph = "_DashedGraph";
                public readonly string _JQPlotAjaxData = "_JQPlotAjaxData";
                public readonly string _JQPlotBarGraph = "_JQPlotBarGraph";
                public readonly string _JQPlotLineGraph = "_JQPlotLineGraph";
                public readonly string _JQPlotMultipleAxes = "_JQPlotMultipleAxes";
                public readonly string _JQPlotNonNumericAxisValues = "_JQPlotNonNumericAxisValues";
                public readonly string _JQPlotOHLCGraph = "_JQPlotOHLCGraph";
                public readonly string _LineGraph = "_LineGraph";
                public readonly string _PagedSetup = "_PagedSetup";
                public readonly string _PieGraph = "_PieGraph";
                public readonly string _PostbackResult = "_PostbackResult";
                public readonly string _SortedSetup = "_SortedSetup";
                public readonly string _StatusSetup = "_StatusSetup";
            }
            public readonly string _AjaxSetup = "~/Views/Core/_AjaxSetup.cshtml";
            public readonly string _BarGraph = "~/Views/Core/_BarGraph.cshtml";
            public readonly string _BasicSetup = "~/Views/Core/_BasicSetup.cshtml";
            public readonly string _CurvedLineGraph = "~/Views/Core/_CurvedLineGraph.cshtml";
            public readonly string _CustomFlotFormatters = "~/Views/Core/_CustomFlotFormatters.cshtml";
            public readonly string _DashedGraph = "~/Views/Core/_DashedGraph.cshtml";
            public readonly string _JQPlotAjaxData = "~/Views/Core/_JQPlotAjaxData.cshtml";
            public readonly string _JQPlotBarGraph = "~/Views/Core/_JQPlotBarGraph.cshtml";
            public readonly string _JQPlotLineGraph = "~/Views/Core/_JQPlotLineGraph.cshtml";
            public readonly string _JQPlotMultipleAxes = "~/Views/Core/_JQPlotMultipleAxes.cshtml";
            public readonly string _JQPlotNonNumericAxisValues = "~/Views/Core/_JQPlotNonNumericAxisValues.cshtml";
            public readonly string _JQPlotOHLCGraph = "~/Views/Core/_JQPlotOHLCGraph.cshtml";
            public readonly string _LineGraph = "~/Views/Core/_LineGraph.cshtml";
            public readonly string _PagedSetup = "~/Views/Core/_PagedSetup.cshtml";
            public readonly string _PieGraph = "~/Views/Core/_PieGraph.cshtml";
            public readonly string _PostbackResult = "~/Views/Core/_PostbackResult.cshtml";
            public readonly string _SortedSetup = "~/Views/Core/_SortedSetup.cshtml";
            public readonly string _StatusSetup = "~/Views/Core/_StatusSetup.cshtml";
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
