#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WebExtras.Core;
    using WebExtras.Mvc.Core;
    using WebExtras.Mvc.Html;
    using WebExtras.Mvc.JQueryUI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/JQueryUI/Views/Core/_AxisLabels.cshtml")]
    public partial class _Areas_JQueryUI_Views_Core__AxisLabels_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_JQueryUI_Views_Core__AxisLabels_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<p>In order to draw axis labels you need <strong>jquery.flot.axislabels.js</stron" +
"g>.</p>\r\n\r\n<div class=\"ui-well\">\r\n  <h4>Drawing axis labels</h4>\r\n  Axis labels " +
"can be drawn by setting the appropriate properties of the <strong>WebExtras.JQFl" +
"ot.SubOptions.AxisOptions</strong> class.\r\n  <pre><code>\r\n  AxisOptions axisOpt " +
"= new AxisOptions\r\n  {\r\n    axisLabel = \"my axis label\"\r\n  };\r\n  </code></pre>\r\n" +
"</div>\r\n\r\n<div class=\"ui-well\">\r\n  <h4>Axis label options</h4>\r\n  <div class=\"co" +
"ntent\">\r\n    <table class=\"ui-table\">\r\n      <tr>\r\n        <th>Option</th>\r\n    " +
"    <th>Type</th>\r\n        <th>Default</th>\r\n        <th style=\"width: 45%\">Desc" +
"ription</th>\r\n      </tr>\r\n      <tr>\r\n        <td>axisLabel</td>\r\n        <td>s" +
"tring</td>\r\n        <td><i>Empty string</i></td>\r\n        <td>Axis label to be s" +
"hown</td>\r\n      </tr>\r\n      <tr>\r\n        <td>axisLabelColor</td>\r\n        <td" +
">string</td>\r\n        <td><i>Color of grid</i></td>\r\n        <td>Axis label colo" +
"r to be used</td>\r\n      </tr>\r\n      <tr>\r\n        <td>axisLabelPadding</td>\r\n " +
"       <td>integer</td>\r\n        <td>2</td>\r\n        <td>Padding, in pixels, bet" +
"ween the tick labels and the axis label</td>\r\n      </tr>\r\n      <tr>\r\n        <" +
"td>axisLabelUseCanvas</td>\r\n        <td>boolean</td>\r\n        <td><i>None</i></t" +
"d>\r\n        <td>Flag indicating whether to use the HTML5 Canvas element to rende" +
"r the axis labels</td>\r\n      </tr>\r\n      <tr>\r\n        <td>axisLabelUseHtml</t" +
"d>\r\n        <td>boolean</td>\r\n        <td>true</td>\r\n        <td>Flag indicating" +
" whether to use HTML and CSS transformations to render the axis labels</td>\r\n   " +
"   </tr>\r\n      <tr>\r\n        <td>axisLabelFontSizePixels</td>\r\n        <td>int<" +
"/td>\r\n        <td>14</td>\r\n        <td>Font size in pixels for the axis label. T" +
"his option is only available if \'axisLabelUseCanvas\' is set to true.</td>\r\n     " +
" </tr>\r\n      <tr>\r\n        <td>axisLabelFontFamily</td>\r\n        <td>string</td" +
">\r\n        <td>sans-serif</td>\r\n        <td>Font family for the axis label. This" +
" option is only available if \'axisLabelUseCanvas\' is set to true.</td>\r\n      </" +
"tr>\r\n    </table>\r\n  </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
