#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\JQueryUI\Views\Core\Datatables.cshtml"
    using WebExtras.Core;
    
    #line default
    #line hidden
    using WebExtras.Mvc.Core;
    using WebExtras.Mvc.Html;
    using WebExtras.Mvc.JQueryUI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/JQueryUI/Views/Core/Datatables.cshtml")]
    public partial class _Areas_JQueryUI_Views_Core_Datatables_cshtml : System.Web.Mvc.WebViewPage<WebExtras.DemoApp.Models.Core.DatatablesViewModel>
    {
        public _Areas_JQueryUI_Views_Core_Datatables_cshtml()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n");


            
            #line 4 "..\..\Areas\JQueryUI\Views\Core\Datatables.cshtml"
  
  ViewBag.Title = "jQuery Datatables";


            
            #line default
            #line hidden
WriteLiteral(@"<h3 class=""keep-center"">jQuery Datatables Bindings</h3>
<div class=""col-group"">
  <div class=""col-6"">
    <div class=""col-12"">
      <div class=""col-3"">
        <strong>Assembly</strong>
      </div>
      <div class=""col-4"">
        WebExtras.dll
      </div>
    </div>
    <div class=""col-12"">
      <div class=""col-3"">
        <strong>Namespace</strong>
      </div>
      <div class=""col-4"">
        WebExtras.JQDataTables
      </div>
    </div>
  </div>
  <div class=""col-offset-7"">
    <div class=""col-4"">
      <strong>Dependancies</strong>
    </div>
    <div class=""col-4"">
      <ul class=""dependancies"">
        <li>jquery.dataTables.js</li>
        <li>jquery.dataTables.css</li>
        <li>jquery.dataTables.jui.css</li>
        <li>webextras.jqueryui.css</li>
      </ul>
    </div>
  </div>
</div>
<div>
  Steps involved in creating a Datatable
    <ul>
      <li>Creating the column definitions</li>
      <li>Creating the table settings</li>
      <li>Creating the table records</li>
      <li>Creating the table object</li>
      <li>And finally the output.....</li>
    </ul>
</div>
<ul class=""ui-nav"">
  <li>");


            
            #line 52 "..\..\Areas\JQueryUI\Views\Core\Datatables.cshtml"
 Write(Html.ActionLink("Basic Setup", MVC.JQueryUI.Core.Datatables()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n  <li>");


            
            #line 53 "..\..\Areas\JQueryUI\Views\Core\Datatables.cshtml"
 Write(Html.ActionLink("Ajax Setup", MVC.JQueryUI.Core.Datatables(1)));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n  <li>");


            
            #line 54 "..\..\Areas\JQueryUI\Views\Core\Datatables.cshtml"
 Write(Html.ActionLink("Paging", MVC.JQueryUI.Core.Datatables(2)));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n  <li>");


            
            #line 55 "..\..\Areas\JQueryUI\Views\Core\Datatables.cshtml"
 Write(Html.ActionLink("Sorting", MVC.JQueryUI.Core.Datatables(3)));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n  <li>");


            
            #line 56 "..\..\Areas\JQueryUI\Views\Core\Datatables.cshtml"
 Write(Html.ActionLink("Adding status column", MVC.JQueryUI.Core.Datatables(4)));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n  <li>");


            
            #line 57 "..\..\Areas\JQueryUI\Views\Core\Datatables.cshtml"
 Write(Html.ActionLink("Adding extra postbacks", MVC.JQueryUI.Core.Datatables(5)));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n</ul>\r\n\r\n<script type=\"text/javascript\">\r\n  $(document).ready(function () " +
"{\r\n    $(\'.ui-nav li:eq(\' + ");


            
            #line 62 "..\..\Areas\JQueryUI\Views\Core\Datatables.cshtml"
                    Write(Model.DisplayMode);

            
            #line default
            #line hidden
WriteLiteral(" + \')\').addClass(\'active\');\r\n  });\r\n</script>\r\n\r\n");


            
            #line 66 "..\..\Areas\JQueryUI\Views\Core\Datatables.cshtml"
 switch (Model.DisplayMode)
{
  case 1:
  
            
            #line default
            #line hidden
            
            #line 69 "..\..\Areas\JQueryUI\Views\Core\Datatables.cshtml"
Write(Html.Partial(MVC.Core.Views._AjaxSetup, Model.Table));

            
            #line default
            #line hidden
            
            #line 69 "..\..\Areas\JQueryUI\Views\Core\Datatables.cshtml"
                                                       
    break;

  case 2:
  
            
            #line default
            #line hidden
            
            #line 73 "..\..\Areas\JQueryUI\Views\Core\Datatables.cshtml"
Write(Html.Partial(MVC.Core.Views._PagedSetup, Model.Table));

            
            #line default
            #line hidden
            
            #line 73 "..\..\Areas\JQueryUI\Views\Core\Datatables.cshtml"
                                                        
    break;

  case 3:
  
            
            #line default
            #line hidden
            
            #line 77 "..\..\Areas\JQueryUI\Views\Core\Datatables.cshtml"
Write(Html.Partial(MVC.Core.Views._SortedSetup, Model.Table));

            
            #line default
            #line hidden
            
            #line 77 "..\..\Areas\JQueryUI\Views\Core\Datatables.cshtml"
                                                         
    break;

  case 4:
  
            
            #line default
            #line hidden
            
            #line 81 "..\..\Areas\JQueryUI\Views\Core\Datatables.cshtml"
Write(Html.Partial(MVC.Core.Views._StatusSetup, Model.Table));

            
            #line default
            #line hidden
            
            #line 81 "..\..\Areas\JQueryUI\Views\Core\Datatables.cshtml"
                                                         
    break;

  case 5:
  
            
            #line default
            #line hidden
            
            #line 85 "..\..\Areas\JQueryUI\Views\Core\Datatables.cshtml"
Write(Html.Partial(MVC.JQueryUI.Core.Views._PostbackSetup, Model));

            
            #line default
            #line hidden
            
            #line 85 "..\..\Areas\JQueryUI\Views\Core\Datatables.cshtml"
                                                              
    break;

  case 6:
  
            
            #line default
            #line hidden
            
            #line 89 "..\..\Areas\JQueryUI\Views\Core\Datatables.cshtml"
Write(Html.Partial(MVC.Core.Views._PostbackResult, Model));

            
            #line default
            #line hidden
            
            #line 89 "..\..\Areas\JQueryUI\Views\Core\Datatables.cshtml"
                                                      
    break;

  case 0:
  default:
  
            
            #line default
            #line hidden
            
            #line 94 "..\..\Areas\JQueryUI\Views\Core\Datatables.cshtml"
Write(Html.Partial(MVC.Core.Views._BasicSetup, Model.Table));

            
            #line default
            #line hidden
            
            #line 94 "..\..\Areas\JQueryUI\Views\Core\Datatables.cshtml"
                                                        
    break;
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
