#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
    using SquishIt.Framework;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
    using SquishIt.Mvc;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
    using WebExtras.Core;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
    using WebExtras.DemoApp.App_Start;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
    using WebExtras.Mvc.Core;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
    using WebExtras.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
    using WebExtras.Mvc.JQueryUI;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/JQueryUI/Views/Shared/_Layout.cshtml")]
    public partial class _Areas_JQueryUI_Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_JQueryUI_Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {







WriteLiteral("\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n  <title>");


            
            #line 12 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
    Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(@" - JQuery UI - WebExtras</title>
  <meta http-equiv=""Content-Type"" content=""text/html; charset=UTF-8"">
  <meta name=""viewport"" content=""width=device-width"" />
  <meta name=""author"" content=""Mihir Mone"" />
  <meta name=""application-name"" content=""WebExtras"" />
  <meta name=""description"" content="".net mvc, .net mvc 4, .net mvc helpers, bootstrap, flot, datatables, gumby"" />
  <link rel=""icon"" type=""image/ico"" href=""");


            
            #line 18 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
                                     Write(Links.Content.favicon_ico);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n\r\n  ");


            
            #line 20 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
Write(Bundle.Css().MvcRenderCachedAssetTag(ContentBundle.CSSJQueryUI.GetStringValue()));

            
            #line default
            #line hidden
WriteLiteral("\r\n  ");


            
            #line 21 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
Write(Bundle.JavaScript().MvcRenderCachedAssetTag(ContentBundle.JSBase.GetStringValue()));

            
            #line default
            #line hidden
WriteLiteral("\r\n  ");


            
            #line 22 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
Write(Bundle.JavaScript().MvcRenderCachedAssetTag(ContentBundle.JSJQueryUI.GetStringValue()));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n  <!--[if lt IE 9]><script language=\"javascript\" type=\"text/javascript\" src=\"" +
"");


            
            #line 24 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
                                                                        Write(Links.Scripts.excanvas_min_js);

            
            #line default
            #line hidden
WriteLiteral("\"></script><![endif]-->\r\n\r\n  ");


            
            #line 26 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral(@"

  <script type=""text/javascript"">
    function goToGoogle() { window.location = ""http://www.google.com.au""; }
    function goToYoutube() { window.location = ""http://www.youtube.com""; }
    function gotoCodeplex() { window.open('http://webextras.codeplex.com/releases', '_blank'); }
    function gotoDownload() { window.open('");


            
            #line 32 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
                                      Write(Url.Action(MVC.JQueryUI.Home.Download()));

            
            #line default
            #line hidden
WriteLiteral(@"', '_self'); }

    $(document).ready(function () {
      $(""#menu"").menubar({
        autoExpand: true
      });

      $('.ui-nav a, .ui-btn').button();
    });
  </script>
</head>
<body>
  <ul id=""menu"" class=""ui-menubar-fixed-top"">
    <li>");


            
            #line 45 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
   Write(Html.Hyperlink("WebExtras", Url.Content("~/")).AddCssClass("brand"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n    <li class=\"");


            
            #line 46 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
          Write(Html.SelectedTab("Home", "Index"));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 46 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
                                              Write(Html.ActionLink("Home", MVC.JQueryUI.Home.Index()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n    <li class=\"");


            
            #line 47 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
          Write(Html.SelectedTab("Core", "Generic"));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 47 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
                                                Write(Html.ActionLink("Core", MVC.JQueryUI.Core.Generic()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n    <li class=\"");


            
            #line 48 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
          Write(Html.SelectedTab("Core", "Datatables"));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 48 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
                                                   Write(Html.ActionLink("jQuery Datatables", MVC.JQueryUI.Core.Datatables()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n    <li class=\"");


            
            #line 49 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
          Write(Html.SelectedTab("Core", new[] { "Flot", "JQPlot" }));

            
            #line default
            #line hidden
WriteLiteral(" dropdown\">\r\n      <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Gra" +
"phs<i class=\"caret\"></i></a>\r\n      <ul class=\"dropdown-menu\">\r\n        <li>");


            
            #line 52 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
       Write(Html.Hyperlink("jQuery Flot", MVC.JQueryUI.Core.Flot()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n        <li>");


            
            #line 53 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
       Write(Html.Hyperlink("jqPlot", MVC.JQueryUI.Core.JQPlot()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n      </ul>\r\n    </li>\r\n\r\n    <li class=\"");


            
            #line 57 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
          Write(Html.SelectedTab("Mvc", new[] { "CoreHtml", "CoreForm" }));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n      <a href=\"#\">Mvc Core</a>\r\n      <ul>\r\n        <li>");


            
            #line 60 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
       Write(Html.ActionLink("Custom Action Results", MVC.JQueryUI.Mvc.ActionResults()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n        <li>");


            
            #line 61 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
       Write(Html.ActionLink("Html extensions", MVC.JQueryUI.Mvc.CoreHtml()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n        <li>");


            
            #line 62 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
       Write(Html.ActionLink("Form extensions", MVC.JQueryUI.Mvc.CoreForm()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n      </ul>\r\n    </li>\r\n    <li class=\"");


            
            #line 65 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
          Write(Html.SelectedTab("Mvc", new[] { "JQueryUIHtml", "JQueryUIForm" }));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n      <a href=\"#\">Mvc JQuery UI</a>\r\n      <ul>\r\n        <li>");


            
            #line 68 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
       Write(Html.ActionLink("Html extensions", MVC.JQueryUI.Mvc.JQueryUIHtml()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n        <li>");


            
            #line 69 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
       Write(Html.ActionLink("Form extensions", MVC.JQueryUI.Mvc.JQueryUIForm()));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n      </ul>\r\n    </li>\r\n    <li class=\"download-btn\">");


            
            #line 72 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
                         Write(Html.Button(EButton.Regular, "Get WebExtras", "gotoDownload()").AddIcon(EJQueryUIIcon.Circle_Arrow_S));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n  </ul>\r\n\r\n  <div class=\"col-12 main\">\r\n    ");


            
            #line 76 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden

            
            #line 76 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
                 WriteLiteral("\r\n  </div>\r\n <footer>\r\n    <span style=\"float: left\" id=\"build-date\">");

            
            #line default
            #line hidden
            
            #line 79 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
                                                 Html.RenderAction(MVC.Flavour.BuildDetails()); 
            
            #line default
            #line hidden
WriteLiteral("</span>\r\n    <span style=\"float: right\">Copyright &copy; ");


            
            #line 80 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
                                           Write(DateTime.Now.Year);

            
            #line default
            #line hidden

            
            #line 80 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
                                                                  WriteLiteral(" Mihir Mone. All Rights Reserved.</span>\r\n    <div>");

            
            #line default
            #line hidden
            
            #line 81 "..\..\Areas\JQueryUI\Views\Shared\_Layout.cshtml"
            Html.RenderAction(MVC.Flavour.VersionDetails()); 
            
            #line default
            #line hidden
WriteLiteral("</div>\r\n  </footer>\r\n</body>\r\n</html>\r\n");


        }
    }
}
#pragma warning restore 1591
